package machinecontract

// Cognition Planner protocol identifiers are the sole machine authority for
// D2-A JSON contracts. Specifications, validators, prompts, and tests consume
// these values instead of maintaining independent copies.
const (
	CognitionBootstrapPlanV1       = "cognition-bootstrap-plan/v1"
	CognitionMigrationPlanV1       = "cognition-migration-plan/v1"
	CognitionSemanticMappingV1     = "cognition-semantic-mapping/v1"
	CognitionLayoutCandidateV1     = "cognition-layout-candidate/v1"
	CognitionLayoutPreviewV1       = "cognition-layout-preview/v1"
	CognitionApprovalDigestV1      = "cognition-approval-digest/v1"
	SemanticAuthoringProvenanceV1  = "semantic-authoring-provenance/v1"
	SemanticAuthoringRequirementV1 = "semantic-authoring-requirement/v1"
	CognitionVolumeRegistryV1      = "cognition-volume-registry/v1"
	BaselineScopePlanV1            = "baseline-scope-plan/v1"
	BaselineScopePreviewV1         = "baseline-scope-preview/v1"
	BaselineScopeApprovalV1        = "baseline-scope-approval/v1"
	BaselineScopeApplyResultV1     = "baseline-scope-apply-result/v1"

	CognitionBootstrapApplyRequestV1      = "cognition-bootstrap-apply-request/v1"
	CognitionBootstrapApplyEnvelopeV1     = "cognition-bootstrap-apply-envelope/v1"
	CognitionBootstrapApprovalV1          = "cognition-bootstrap-approval/v1"
	CognitionBootstrapAutoEligibilityV1   = "cognition-bootstrap-auto-eligibility/v1"
	CognitionBootstrapRecoveryV1          = "cognition-bootstrap-recovery/v1"
	CognitionBootstrapApplyResultV1       = "cognition-bootstrap-apply-result/v1"
	CognitionBootstrapTransactionStatusV1 = "cognition-bootstrap-transaction-status/v1"
	CognitionBootstrapValidatorV1         = "bootstrap-apply-validator/v1"
	DatabaseCognitionBootstrapPreviewV1   = "database-cognition-bootstrap-preview/v1"
	DatabaseCognitionBootstrapRecoveryV1  = "database-cognition-bootstrap-recovery/v1"
	DatabaseCognitionBootstrapResultV1    = "database-cognition-bootstrap-result/v1"

	CognitionLegacySnapshotV1             = "cognition-legacy-snapshot/v1"
	CognitionMigrationMappingV1           = "cognition-migration-mapping/v1"
	CognitionMigrationApplyRequestV1      = "cognition-migration-apply-request/v1"
	CognitionMigrationApplyEnvelopeV1     = "cognition-migration-apply-envelope/v1"
	CognitionMigrationApprovalV1          = "cognition-migration-approval/v1"
	CognitionMigrationRecoveryV1          = "cognition-migration-recovery/v1"
	CognitionMigrationReceiptV1           = "cognition-migration-receipt/v1"
	CognitionMigrationApplyResultV1       = "cognition-migration-apply-result/v1"
	CognitionMigrationTransactionStatusV1 = "cognition-migration-transaction-status/v1"
	CognitionMigrationReversalPlanV1      = "cognition-migration-reversal-plan/v1"
	CognitionMigrationReversalApprovalV1  = "cognition-migration-reversal-approval/v1"
	CognitionMigrationReversalRecoveryV1  = "cognition-migration-reversal-recovery/v1"
	CognitionMigrationValidatorV1         = "migration-apply-validator/v1"

	// RC17 changes Migration content identity, field-preservation evidence, and
	// replay diagnostics. V1 constants remain named for historical artifact
	// identification, but current Prepare/Apply accepts only this explicit v2
	// family so an rc16 Envelope or Approval cannot authorize rc17 bytes.
	CognitionMigrationPlanV2              = "cognition-migration-plan/v2"
	CognitionMigrationMappingV2           = "cognition-migration-mapping/v2"
	CognitionMigrationApplyRequestV2      = "cognition-migration-apply-request/v2"
	CognitionMigrationApplyEnvelopeV2     = "cognition-migration-apply-envelope/v2"
	CognitionMigrationApprovalV2          = "cognition-migration-approval/v2"
	CognitionMigrationRecoveryV2          = "cognition-migration-recovery/v2"
	CognitionMigrationReceiptV2           = "cognition-migration-receipt/v2"
	CognitionMigrationApplyResultV2       = "cognition-migration-apply-result/v2"
	CognitionMigrationTransactionStatusV2 = "cognition-migration-transaction-status/v2"
	CognitionMigrationReversalPlanV2      = "cognition-migration-reversal-plan/v2"
	CognitionMigrationReversalApprovalV2  = "cognition-migration-reversal-approval/v2"
	CognitionMigrationReversalRecoveryV2  = "cognition-migration-reversal-recovery/v2"
	CognitionMigrationValidatorV2         = "migration-apply-validator/v2"

	CognitionOperationBootstrap         = "bootstrap"
	CognitionOperationDatabaseBootstrap = "database_bootstrap"
	CognitionOperationMigration         = "migration"
	CognitionOperationMigrationReversal = "migration_reversal"

	CognitionMigrationRecoveryPolicy                = "restore_exact_legacy_preimage"
	CognitionMigrationReversalPolicy                = "strict_receipt_bound_reversal"
	CognitionMigrationApprovalMechanism             = "interactive_digest_confirmation"
	CognitionMigrationRecoveryDirection             = "volume_postimage_to_legacy_preimage"
	CognitionMigrationReversalDirection             = "migration_postimage_to_legacy_preimage"
	CognitionMigrationLegacyPreimage                = "legacy_sha256"
	CognitionMigrationBaselinePreimage              = "baseline_sha256"
	CognitionMigrationSemanticReviewed              = "reviewed"
	CognitionMigrationSemanticPending               = "pending"
	CognitionMigrationModelRegenerated              = "model_regenerated"
	CognitionMigrationEligibilityEligible           = "eligible"
	CognitionMigrationEligibilityIneligible         = "ineligible"
	CognitionMigrationStatusPrepared                = "prepared"
	CognitionMigrationStatusRecoveryRequiredLegacy  = "recovery_required_legacy_active"
	CognitionMigrationStatusRecoveryRequiredVolumes = "recovery_required_volumes_active"
	CognitionMigrationStatusRecoveryConflict        = "recovery_conflict"
	CognitionMigrationStatusApplied                 = "applied"
	CognitionMigrationStatusAlreadyApplied          = "already_applied"
	CognitionMigrationStatusRolledBack              = "rolled_back"
	CognitionMigrationStatusReversed                = "reversed"
	CognitionMigrationStatusAlreadyReversed         = "already_reversed"

	CognitionBootstrapPreimageAbsent          = "absent"
	CognitionBootstrapPreimageOfficialMinimal = "official_minimal_skeleton"
	CognitionBootstrapRecoveryPolicy          = "incomplete_bootstrap_only"
	CognitionBootstrapApprovalMechanism       = "interactive_digest_confirmation"
	CognitionBootstrapAutoApprovalMechanism   = "policy_bound_auto"
	CognitionAutomationPolicyTeamConfig       = "team_config"
	CognitionAutomationPolicyFreshDefault     = "fresh_bootstrap_default"
	CognitionAutomationPolicyLegacy           = "legacy_compatibility"
	CognitionAutomationPolicyPersistedLegacy  = "persisted_session_compatibility"
	CognitionBootstrapRecoveryDirection       = "postimage_to_absent_preimage"

	CognitionAutoBlockerPolicyNotAuto      = "automation_policy_not_auto"
	CognitionAutoBlockerPolicyDrift        = "automation_policy_drift"
	CognitionAutoBlockerNotFresh           = "fresh_bootstrap_required"
	CognitionAutoBlockerSensitiveRead      = "sensitive_read_or_scope_expansion"
	CognitionAutoBlockerProvenance         = "semantic_authoring_provenance_invalid"
	CognitionAutoBlockerPreview            = "preview_not_ready"
	CognitionAutoBlockerRisk               = "preview_risk_present"
	CognitionAutoBlockerPlanDrift          = "plan_superseded"
	CognitionAutoBlockerSourceDrift        = "source_drift"
	CognitionAutoBlockerFormalState        = "formal_cognition_already_present"
	CognitionAutoBlockerGovernanceHistory  = "mature_governance_history_present"
	CognitionAutoBlockerRecovery           = "recovery_uncertain"
	CognitionAutoBlockerCAS                = "cas_unavailable_or_conflict"
	CognitionAutoBlockerDatabaseEvidence   = "database_evidence_not_current"
	CognitionAutoBlockerDatabaseSideEffect = "database_side_effect"
	CognitionAutoBlockerNetworkSideEffect  = "external_network_side_effect"

	CognitionBootstrapDiskPreimage       = "preimage"
	CognitionBootstrapDiskPostimage      = "postimage"
	CognitionBootstrapDiskUnknown        = "unknown"
	CognitionBootstrapDiskWrongType      = "wrong_type"
	CognitionBootstrapDiskMissingStaging = "missing_staging"

	CognitionBootstrapStatusPrepared                 = "prepared"
	CognitionBootstrapStatusRecoveryRequiredInactive = "recovery_required_inactive"
	CognitionBootstrapStatusRecoveryRequiredActive   = "recovery_required_active"
	CognitionBootstrapStatusRecoveryConflict         = "recovery_conflict"
	CognitionBootstrapStatusApplied                  = "applied"
	CognitionBootstrapStatusAlreadyApplied           = "already_applied"
	CognitionBootstrapStatusRolledBack               = "rolled_back"

	DatabaseCognitionBootstrapStatusPrepared       = "prepared"
	DatabaseCognitionBootstrapStatusApplied        = "applied"
	DatabaseCognitionBootstrapStatusAlreadyApplied = "already_applied"
	DatabaseCognitionBootstrapStatusRolledBack     = "rolled_back"

	CognitionPlannerUninitialized = "uninitialized"
	CognitionPlannerLegacy        = "legacy"
	CognitionPlannerVolumes       = "volumes"

	CognitionPlannerAuthoringRequired = "model_authoring_required"
	CognitionPlannerPreviewReady      = "preview_ready"
	CognitionPlannerMigrationRequired = "migration_required"
	CognitionPlannerBootstrapRequired = "bootstrap_required"
	CognitionPlannerAlreadyVolumes    = "layout_already_volumes"
	CognitionPlannerSuperseded        = "superseded"
	CognitionPlannerInvalid           = "invalid"

	SemanticAuthoringOriginHostModel = "host_model"
	SemanticAuthoringStatusVerified  = "verified"

	CognitionMappingPreserved                 = "preserved"
	CognitionMappingFieldPreserved            = "field_preserved"
	CognitionMappingModelRegenerationRequired = "model_regeneration_required"
	CognitionMappingStructuralOnly            = "structural_only"
	CognitionSemanticEquivalenceUnverified    = "semantic_equivalence_unverified"
	CognitionSemanticReviewIncomplete         = "semantic_review_incomplete"
	CognitionLegacyEntryDispositionV1         = "legacy-entry-disposition/v1"
	CognitionEntryPreservationV1              = "entry-preservation/v1"

	CognitionVolumeEnabled  = "enabled"
	CognitionVolumeDisabled = "disabled"
)
