package cli

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/aoci-spec/aoci-code/internal/cognition"
	"github.com/aoci-spec/aoci-code/internal/config"
	"github.com/aoci-spec/aoci-code/internal/curation"
	"github.com/aoci-spec/aoci-code/internal/hooks"
	"github.com/aoci-spec/aoci-code/internal/index"
	"github.com/aoci-spec/aoci-code/textassets"
)

// prepareLocaleChange changes only configuration state. Existing formal
// assets are inventoried into a resumable receipt and remain untouched until
// the regular Header, Entries, and Curation governance pipelines apply their
// reviewed replacements.
func prepareLocaleChange(root string, cfg *config.Config, target string) error {
	if cfg == nil {
		return errors.New(cliMessage("locale.config_unavailable"))
	}
	if cfg.LocaleMigration != nil {
		if cfg.LocaleMigration.ToLocale == target && cfg.Locale == target {
			return nil
		}
		return errors.New(cliMessage(
			"locale.migration_in_progress",
			cfg.LocaleMigration.FromLocale,
			cfg.LocaleMigration.ToLocale,
		))
	}
	indexPath := filepath.Join(root, filepath.FromSlash(cfg.IndexPath))
	data, err := os.ReadFile(indexPath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			cfg.Locale = target
			return nil
		}
		return errors.New(cliMessage("locale.read_index_error", err))
	}
	layout, err := cognition.DetectLayout(data)
	if err != nil {
		return errors.New(cliMessage("locale.detect_index_error", err))
	}
	if layout == cognition.LayoutVolumesV1 {
		if _, loadErr := cognition.Load(root, cfg.IndexPath); loadErr != nil {
			return errors.New(cliMessage(
				"locale.volume_invalid",
				localeSafeCLIDetail(loadErr.Error()),
			))
		}
		// The enclosing Locale transaction changes only Root's deterministic
		// #Locale marker. Meta and object-Volume bytes remain unchanged; only a
		// genuine later Entry update writes that Entry in the new Locale.
		cfg.Locale = target
		return nil
	}

	fromLocale, _, err := index.DetectLocale(string(data))
	if err != nil {
		return errors.New(cliMessage("locale.detect_index_error", err))
	}
	if fromLocale == target {
		cfg.Locale = target
		cfg.LocaleMigration = nil
		return nil
	}

	document, _ := index.Parse(string(data))
	index.ResolveRelPaths(document, root)
	governanceEntrySet := map[string]struct{}{}
	for _, section := range document.Sections {
		for _, entry := range section.Entries {
			if entry.RelPath == "" {
				return errors.New(cliMessage(
					"locale.unresolved_entry",
					entry.Filename,
				))
			}
			if isAOCIGovernanceEntryPath(entry.RelPath) {
				governanceEntrySet[entry.RelPath] = struct{}{}
			}
		}
	}

	curationDocument, _, _, err := curation.Load(root)
	if err != nil {
		return errors.New(cliMessage("locale.read_curation_error", err))
	}
	curationSet := map[string]struct{}{}
	for _, decision := range curationDocument.Decisions {
		if _, profileErr := curation.ProfilePath(root, decision.Path); profileErr != nil {
			return errors.New(cliMessage(
				"locale.unavailable_curation",
				decision.Path,
				profileErr,
			))
		}
		curationSet[decision.Path] = struct{}{}
	}

	cfg.Locale = target
	cfg.LocaleMigration = &config.LocaleMigration{
		Version:       2,
		FromLocale:    fromLocale,
		ToLocale:      target,
		HeaderPending: true,
		HeaderTotal:   1,
		// Existing ordinary Entries are intentionally prospective: changing the
		// unified Locale does not translate them in bulk. New and genuinely
		// updated Entries use the active Locale through the normal authoring path.
		EntryPaths:                []string{},
		EntryTotal:                0,
		GovernanceEntryPaths:      sortedLocaleMigrationPaths(governanceEntrySet),
		GovernanceEntryTotal:      len(governanceEntrySet),
		CurationPaths:             sortedLocaleMigrationPaths(curationSet),
		CurationTotal:             len(curationSet),
		ManagedIndexTextPending:   true,
		ManagedIndexTextTotal:     countManagedIndexTextTargets(document),
		AgentsManagedBlockPending: true,
		AgentsManagedBlockTotal:   1,
	}
	return nil
}

// isAOCIGovernanceEntryPath identifies repository-internal machine governance
// assets. They are not source-semantic Entry targets: their append-only or
// machine-generated bytes must never be used as locale-migration evidence.
func isAOCIGovernanceEntryPath(relPath string) bool {
	relPath = strings.TrimPrefix(filepath.ToSlash(strings.TrimSpace(relPath)), "./")
	return relPath == config.DirName || strings.HasPrefix(relPath, config.DirName+"/")
}

// countManagedIndexTextTargets counts the formal non-Entry surfaces after the
// Header. Every directory-section line and every non-empty explanatory line is
// one target; path tokens remain protected during candidate validation.
func countManagedIndexTextTargets(document *index.Document) int {
	if document == nil {
		return 0
	}
	entryLines := map[int]struct{}{}
	for _, section := range document.Sections {
		for _, entry := range section.Entries {
			entryLines[entry.LineNo] = struct{}{}
		}
	}
	count := 0
	for _, section := range document.Sections {
		for offset, line := range section.RawLines {
			lineNo := section.StartLine + offset
			if _, entry := entryLines[lineNo]; entry || strings.TrimSpace(line) == "" {
				continue
			}
			count++
		}
	}
	return count
}

// ensureManagedAgentsLocale rewrites only the AOCI-managed AGENTS block from
// the target catalog. Locale migration cannot clear its Header prerequisite
// until this deterministic project contract is also in the target language.
func ensureManagedAgentsLocale(root, locale string) error {
	previous := textassets.ActiveLocale()
	if err := textassets.SetActiveLocale(locale); err != nil {
		return err
	}
	_, updateErr := hooks.EnsureAgentsBlock(root)
	restoreErr := textassets.SetActiveLocale(previous)
	if updateErr != nil {
		return updateErr
	}
	return restoreErr
}

func sortedLocaleMigrationPaths(paths map[string]struct{}) []string {
	result := make([]string, 0, len(paths))
	for path := range paths {
		result = append(result, path)
	}
	sort.Strings(result)
	return result
}

func splitLocaleMigrationEntryPaths(migration *config.LocaleMigration) (ordinary, governance []string) {
	if migration == nil {
		return nil, nil
	}
	governanceSet := map[string]struct{}{}
	for _, relPath := range migration.GovernanceEntryPaths {
		governanceSet[relPath] = struct{}{}
	}
	for _, relPath := range migration.EntryPaths {
		if isAOCIGovernanceEntryPath(relPath) {
			governanceSet[relPath] = struct{}{}
			continue
		}
		ordinary = append(ordinary, relPath)
	}
	governance = sortedLocaleMigrationPaths(governanceSet)
	return ordinary, governance
}

func buildLocaleMigrationCoverage(cfg *config.Config) localeMigrationCoverage {
	coverage := localeMigrationCoverage{
		Excluded: []localeMigrationExclusion{
			{Surface: "paths_identifiers_apis_and_project_names", Reason: cliMessage("locale.coverage.exclude_identity")},
			{Surface: "source_and_source_comments", Reason: cliMessage("locale.coverage.exclude_source")},
			{Surface: "agents_unmanaged_region_and_user_documents", Reason: cliMessage("locale.coverage.exclude_user")},
		},
		Unresolved: []localeMigrationUnresolved{},
	}
	if cfg == nil || cfg.LocaleMigration == nil {
		coverage.AgentsManagedBlock.Status = "aligned"
		coverage.RuntimeContracts.Status = "aligned"
		return coverage
	}
	migration := cfg.LocaleMigration
	ordinary, governance := splitLocaleMigrationEntryPaths(migration)
	ordinaryTotal := migration.EntryTotal
	legacyGovernance := len(migration.EntryPaths) - len(ordinary)
	if legacyGovernance > 0 && migration.GovernanceEntryTotal == 0 {
		ordinaryTotal -= legacyGovernance
	}
	governanceTotal := migration.GovernanceEntryTotal
	if governanceTotal < len(governance) {
		governanceTotal = len(governance)
	}
	coverage.Active = true
	coverage.FromLocale = migration.FromLocale
	coverage.ToLocale = migration.ToLocale
	coverage.Header = localeMigrationCoverageCount{Total: migration.HeaderTotal, Pending: boolCount(migration.HeaderPending)}
	coverage.OrdinaryEntries = localeMigrationCoverageCount{Total: ordinaryTotal, Pending: len(ordinary)}
	coverage.GovernanceEntries = localeMigrationCoverageCount{Total: governanceTotal, Pending: len(governance)}
	coverage.Curation = localeMigrationCoverageCount{Total: migration.CurationTotal, Pending: len(migration.CurationPaths)}
	coverage.ManagedIndexText = localeMigrationCoverageCount{Total: migration.ManagedIndexTextTotal, Pending: pendingTotal(migration.ManagedIndexTextPending, migration.ManagedIndexTextTotal)}
	coverage.AgentsManagedBlock = localeMigrationCoverageStatus{Total: migration.AgentsManagedBlockTotal, Pending: boolCount(migration.AgentsManagedBlockPending), Status: pendingStatus(migration.AgentsManagedBlockPending)}
	coverage.RuntimeContracts = localeMigrationCoverageStatus{Total: 1, Pending: 0, Status: "target_locale_catalog_active"}
	appendUnresolved := func(target string, count int, reason string) {
		if count > 0 {
			coverage.Unresolved = append(coverage.Unresolved, localeMigrationUnresolved{Target: target, Count: count, Reason: reason})
		}
	}
	appendUnresolved("header", coverage.Header.Pending, cliMessage("locale.coverage.pending_header"))
	appendUnresolved("ordinary_entries", coverage.OrdinaryEntries.Pending, cliMessage("locale.coverage.pending_entries"))
	appendUnresolved("governance_entries", coverage.GovernanceEntries.Pending, cliMessage("locale.coverage.pending_governance"))
	appendUnresolved("curation", coverage.Curation.Pending, cliMessage("locale.coverage.pending_curation"))
	appendUnresolved("managed_index_text", coverage.ManagedIndexText.Pending, cliMessage("locale.coverage.pending_index_text"))
	appendUnresolved("agents_managed_block", coverage.AgentsManagedBlock.Pending, cliMessage("locale.coverage.pending_agents"))
	return coverage
}

func boolCount(value bool) int {
	if value {
		return 1
	}
	return 0
}

func pendingTotal(pending bool, total int) int {
	if pending {
		return total
	}
	return 0
}

func pendingStatus(pending bool) string {
	if pending {
		return "pending"
	}
	return "aligned"
}

func localeMigrationContainsOrdinaryEntry(cfg *config.Config, relPath string) bool {
	if cfg == nil || cfg.LocaleMigration == nil {
		return false
	}
	ordinary, _ := splitLocaleMigrationEntryPaths(cfg.LocaleMigration)
	for _, pending := range ordinary {
		if pending == relPath {
			return true
		}
	}
	return false
}

var localeTechnicalTokenRE = regexp.MustCompile(`--?[A-Za-z0-9][A-Za-z0-9_-]*|[A-Za-z0-9_][A-Za-z0-9_-]*(?:[./:@#%+<>=][A-Za-z0-9_-]+)*`)

// validateLocaleEntryProtectedFacts keeps repository identity separate from
// natural-language migration in every F/R/A/S field. The complete R and A
// strings cannot be frozen because existing indexes legitimately contain
// prose beside relationship and API facts. Instead, the Locale gate preserves
// mechanically identifiable paths, flags, numbers, code identifiers, API
// names, and stable product names while allowing the surrounding prose to move
// to the target Locale. Project-specific names that have no lexical distinction
// from ordinary prose remain part of the model's semantic review obligation.
func validateLocaleEntryProtectedFacts(oldLine, newLine string) error {
	return validateLocaleEntryProtectedFactsWithEvidence(oldLine, newLine, nil)
}

func validateLocaleEntryProtectedFactsWithEvidence(oldLine, newLine string, sourceEvidence []byte) error {
	parse := func(line string) *index.Entry {
		document, _ := index.Parse("===root /locale-validation/===\n" + line + "\n")
		if len(document.Sections) == 1 && len(document.Sections[0].Entries) == 1 {
			return document.Sections[0].Entries[0]
		}
		return nil
	}
	oldEntry := parse(oldLine)
	newEntry := parse(newLine)
	if oldEntry == nil || newEntry == nil {
		return errors.New(cliMessage("locale.protected.parse_failed"))
	}
	if oldEntry.Filename != newEntry.Filename {
		return fmt.Errorf("%s", cliMessage(
			"locale.protected.filename_changed", oldEntry.Filename, newEntry.Filename,
		))
	}
	if oldEntry.TagsRaw != newEntry.TagsRaw {
		return fmt.Errorf("%s", cliMessage("locale.protected.tags_changed", oldEntry.Filename))
	}
	oldFacts := localeEntryTechnicalFacts(oldEntry)
	if sourceEvidence != nil {
		oldFacts = localeEvidenceBoundFacts(oldFacts, string(sourceEvidence))
	}
	newFacts := localeEntryTechnicalFacts(newEntry)
	if !containsStringCounts(newFacts, oldFacts) {
		return fmt.Errorf("%s", cliMessage(
			"locale.protected.facts_changed",
			oldEntry.Filename,
			sortedStringCounts(oldFacts),
			sortedStringCounts(newFacts),
		))
	}
	return nil
}

func localeEvidenceBoundFacts(facts map[string]int, sourceEvidence string) map[string]int {
	result := make(map[string]int, len(facts))
	for fact, count := range facts {
		if localeEvidenceContainsFact(sourceEvidence, fact) || localeRepositoryPathFact(fact) {
			result[fact] = count
		}
	}
	return result
}

func localeEvidenceContainsFact(sourceEvidence, fact string) bool {
	for offset := 0; offset <= len(sourceEvidence)-len(fact); {
		position := strings.Index(sourceEvidence[offset:], fact)
		if position < 0 {
			return false
		}
		position += offset
		end := position + len(fact)
		leftOK := position == 0 || !localeTechnicalByte(sourceEvidence[position-1])
		rightOK := end == len(sourceEvidence) || !localeTechnicalByte(sourceEvidence[end])
		if leftOK && rightOK {
			return true
		}
		offset = position + 1
	}
	return false
}

func localeTechnicalByte(value byte) bool {
	return (value >= 'A' && value <= 'Z') || (value >= 'a' && value <= 'z') ||
		(value >= '0' && value <= '9') || strings.ContainsRune("_./:@#%+<>=-", rune(value))
}

func localeRepositoryPathFact(token string) bool {
	if localeDotTechnicalToken(token) {
		return true
	}
	if !strings.Contains(token, "/") {
		return false
	}
	first := strings.TrimPrefix(strings.Split(token, "/")[0], ".")
	switch first {
	case "cmd", "docs", "internal", "reference", "scripts", "spec", "testdata", "textassets", "build", "dist", "github.com":
		return true
	default:
		return false
	}
}

func localeEntryTechnicalFacts(entry *index.Entry) map[string]int {
	result := map[string]int{}
	fields := []struct {
		name  string
		value string
	}{
		{name: "F", value: entry.F},
		{name: "R", value: entry.R},
		{name: "A", value: entry.Api},
		{name: "S", value: entry.S},
	}
	for _, field := range fields {
		matches := localeTechnicalTokenRE.FindAllStringIndex(field.value, -1)
		for _, match := range matches {
			token := field.value[match[0]:match[1]]
			if localeTechnicalToken(field.name, field.value, match[0], match[1], token) {
				result[token]++
			}
		}
	}
	return result
}

func localeTechnicalToken(field, value string, start, end int, token string) bool {
	if token == "" {
		return false
	}
	if strings.HasPrefix(token, "-") && localeFlagBoundary(value, start) {
		return true
	}
	if strings.ContainsAny(token, "_:@#%+<>=") {
		return true
	}
	if strings.Contains(token, ".") {
		return localeDotTechnicalToken(token)
	}
	if strings.Contains(token, "/") {
		return localeSlashTechnicalToken(token)
	}
	if localeLetterDigitIdentifier(token) {
		return true
	}
	// Plain hyphenated target-locale prose such as "full-silo" or
	// "Cross-Compilation" is not an identifier merely because English uses a
	// hyphen. Flags and code-like letter-digit identifiers were handled above.
	if strings.Contains(token, "-") {
		return false
	}
	hasLower := strings.IndexFunc(token, func(r rune) bool { return r >= 'a' && r <= 'z' }) >= 0
	if hasLower {
		for position := 1; position < len(token); position++ {
			if token[position] >= 'A' && token[position] <= 'Z' {
				return true
			}
		}
	}
	if end < len(value) && value[end] == '(' {
		return true
	}
	if field == "A" {
		left := strings.LastIndexAny(value[:start], ",;") + 1
		right := len(value)
		if next := strings.IndexAny(value[end:], ",;"); next >= 0 {
			right = end + next
		}
		if strings.TrimSpace(value[left:right]) == token && token[0] >= 'A' && token[0] <= 'Z' {
			return true
		}
	}
	if localeKnownTechnicalName(token) {
		return true
	}
	return false
}

func localeFlagBoundary(value string, start int) bool {
	if start == 0 {
		return true
	}
	previous := value[start-1]
	return previous >= 0x80 || previous == ' ' || previous == '\t' || strings.ContainsRune("([{:;,", rune(previous))
}

func localeLetterDigitIdentifier(token string) bool {
	if token == "" || !((token[0] >= 'A' && token[0] <= 'Z') || (token[0] >= 'a' && token[0] <= 'z')) {
		return false
	}
	return strings.IndexFunc(token, func(r rune) bool { return r >= '0' && r <= '9' }) >= 0
}

func localeSlashTechnicalToken(token string) bool {
	parts := strings.Split(token, "/")
	if len(parts) < 2 {
		return false
	}
	first := strings.TrimPrefix(parts[0], ".")
	switch first {
	case "cmd", "docs", "internal", "reference", "scripts", "spec", "testdata", "textassets", "build", "dist", "github.com":
		return true
	}
	for _, part := range parts {
		if strings.ContainsAny(part, "_:@#%+<>=") || localeDotTechnicalToken(part) || localeLetterDigitIdentifier(part) || localeKnownTechnicalName(part) {
			return true
		}
		if len(part) <= 4 && len(part) > 0 && part == strings.ToUpper(part) {
			return true
		}
	}
	return false
}

func localeDotTechnicalToken(token string) bool {
	if token == "" || token == "i.e" || token == "e.g" {
		return false
	}
	if strings.HasPrefix(token, ".") || token == "github.com" {
		return true
	}
	parts := strings.Split(token, ".")
	if len(parts) < 2 {
		return false
	}
	switch strings.ToLower(parts[len(parts)-1]) {
	case "go", "json", "jsonl", "txt", "md", "yml", "yaml", "sh", "py", "toml", "mod", "sum", "exe", "tmpl", "sha256":
		return true
	}
	for _, part := range parts {
		if strings.Contains(part, "_") || localeLetterDigitIdentifier(part) {
			return true
		}
		if part != "" && part[0] >= 'A' && part[0] <= 'Z' {
			return true
		}
	}
	return false
}

func localeKnownTechnicalName(token string) bool {
	switch token {
	case "AOCI", "AGENTS", "API", "CLI", "MCP", "LLM", "JSON", "JSONL", "SHA", "CAS", "CRLF", "LF", "ID", "ASCII", "Go", "Git", "GitHub", "Codex", "Claude", "Cobra", "Linux", "Windows", "SQLite", "PowerShell", "macOS":
		return true
	default:
		return false
	}
}

func containsStringCounts(candidate, required map[string]int) bool {
	for value := range required {
		if candidate[value] == 0 {
			return false
		}
	}
	return true
}

func sortedStringCounts(values map[string]int) []string {
	result := make([]string, 0, len(values))
	for value, count := range values {
		if count == 1 {
			result = append(result, value)
		} else {
			result = append(result, fmt.Sprintf("%s(x%d)", value, count))
		}
	}
	sort.Strings(result)
	return result
}

type localeIndexCandidateSummary struct {
	OrdinaryEntries   int
	GovernanceEntries int
	ManagedText       int
}

// validateLocaleIndexCandidate proves that the Header-stage full-index
// candidate changes only AOCI-managed explanatory text and explicitly removes
// the receipt-bound legacy .aoci Entries. Ordinary Entries remain byte-for-byte
// unchanged; only a later genuine source-bound update may rewrite one in the
// then-active unified Locale.
func validateLocaleIndexCandidate(
	currentText,
	candidateText,
	repoRoot,
	targetLocale string,
	migration *config.LocaleMigration,
) (localeIndexCandidateSummary, error) {
	if migration == nil {
		return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage("locale.candidate.migration_required"))
	}
	candidateHeader, _ := index.ExtractHeader(candidateText)
	candidateLocale, explicit, err := index.DetectLocale(candidateHeader)
	if err != nil || !explicit || candidateLocale != targetLocale {
		if err == nil {
			err = fmt.Errorf("%s", cliMessage("locale.candidate.marker_required", targetLocale))
		}
		return localeIndexCandidateSummary{}, err
	}

	current, _ := index.Parse(currentText)
	candidate, warnings := index.Parse(candidateText)
	if len(warnings) > 0 {
		return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage(
			"locale.candidate.parser_warning", localeSafeCLIDetail(warnings[0].Msg),
		))
	}
	index.ResolveRelPaths(current, repoRoot)
	index.ResolveRelPaths(candidate, repoRoot)

	if len(current.Sections) != len(candidate.Sections) {
		return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage("locale.candidate.section_count_changed"))
	}
	for position := range current.Sections {
		if current.Sections[position].AbsPath != candidate.Sections[position].AbsPath {
			return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage(
				"locale.candidate.directory_path_changed",
				position+1,
				current.Sections[position].AbsPath,
				candidate.Sections[position].AbsPath,
			))
		}
	}

	ordinaryPending, governancePending := splitLocaleMigrationEntryPaths(migration)
	ordinarySet := makeStringSet(ordinaryPending)
	governanceSet := makeStringSet(governancePending)
	currentOrdinary := map[string]string{}
	currentGovernance := map[string]string{}
	for _, section := range current.Sections {
		for _, entry := range section.Entries {
			if entry.RelPath == "" {
				return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage(
					"locale.candidate.current_path_unresolved", entry.Filename,
				))
			}
			if isAOCIGovernanceEntryPath(entry.RelPath) {
				if _, expected := governanceSet[entry.RelPath]; !expected {
					return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage(
						"locale.candidate.governance_unreceipted", entry.RelPath,
					))
				}
				currentGovernance[entry.RelPath] = entry.FullLine
				continue
			}
			currentOrdinary[entry.RelPath] = entry.FullLine
		}
	}
	if len(currentGovernance) != len(governanceSet) {
		return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage("locale.candidate.governance_receipt_mismatch"))
	}
	candidateOrdinary := map[string]string{}
	for _, section := range candidate.Sections {
		for _, entry := range section.Entries {
			if entry.RelPath == "" {
				return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage(
					"locale.candidate.candidate_path_unresolved", entry.Filename,
				))
			}
			if isAOCIGovernanceEntryPath(entry.RelPath) {
				return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage(
					"locale.candidate.legacy_governance_retained", entry.RelPath,
				))
			}
			candidateOrdinary[entry.RelPath] = entry.FullLine
		}
	}
	if len(currentOrdinary) != len(candidateOrdinary) {
		return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage("locale.candidate.ordinary_set_changed"))
	}
	for relPath, oldLine := range currentOrdinary {
		newLine, present := candidateOrdinary[relPath]
		if !present || newLine != oldLine {
			return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage(
				"locale.candidate.ordinary_changed_early", relPath,
			))
		}
	}
	for relPath := range ordinarySet {
		if _, present := currentOrdinary[relPath]; !present {
			return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage(
				"locale.candidate.ordinary_missing", relPath,
			))
		}
	}

	managedCount := countManagedIndexTextTargets(candidate)
	if managedCount != migration.ManagedIndexTextTotal {
		return localeIndexCandidateSummary{}, fmt.Errorf("%s", cliMessage(
			"locale.candidate.managed_count_changed",
			managedCount,
			migration.ManagedIndexTextTotal,
		))
	}
	return localeIndexCandidateSummary{
		OrdinaryEntries:   len(currentOrdinary),
		GovernanceEntries: len(currentGovernance),
		ManagedText:       managedCount,
	}, nil
}

func makeStringSet(values []string) map[string]struct{} {
	result := make(map[string]struct{}, len(values))
	for _, value := range values {
		result[strings.TrimSpace(value)] = struct{}{}
	}
	return result
}
