//go:build integration

package dbevidence

import (
	"bytes"
	"context"
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"database/sql"
	"encoding/base64"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"math/big"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	opengauss "gitcode.com/opengauss/openGauss-connector-go-pq"
	mysqlDriver "github.com/go-sql-driver/mysql"
)

const businessSentinel = "AOCI_BUSINESS_ROW_SENTINEL_D0"

type realAcceptanceGolden struct {
	Version string                     `json:"version"`
	Engines []realAcceptanceEngineGold `json:"engines"`
}

type realAcceptanceEngineGold struct {
	Engine               string       `json:"engine"`
	ObjectRef            string       `json:"object_ref"`
	CanonicalEvidenceRef string       `json:"canonical_evidence_ref"`
	TableEvidenceSHA256  string       `json:"table_evidence_sha256"`
	SourceSnapshotSHA256 string       `json:"source_snapshot_sha256"`
	TableCount           int          `json:"table_count"`
	Drift                DriftSummary `json:"drift"`
}

func TestOpenGaussRandomCredentialContract(t *testing.T) {
	first := openGaussRandomCredential(t)
	second := openGaussRandomCredential(t)
	if first == second || len(first) != 26 || len(second) != 26 {
		t.Fatal("openGauss fixture credentials are not bounded and randomized")
	}
}

func TestPostgreSQLRealCatalogCollectionAndDrift(t *testing.T) {
	adminDSN := postgresqlAdminDSN(t)
	credentialSentinel := randomCredential(t)
	readerDSN := postgresqlUserDSN(t, adminDSN, "aoci_d0_reader", credentialSentinel)
	admin, err := sql.Open("pgx", adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close()
	postgresSetup := []string{
		`DROP SCHEMA IF EXISTS aoci_d0 CASCADE`,
		`DROP SCHEMA IF EXISTS "Quoted Schema" CASCADE`,
		`CREATE SCHEMA aoci_d0`,
		`CREATE SCHEMA "Quoted Schema"`,
		`CREATE TABLE aoci_d0.accounts (id bigint GENERATED BY DEFAULT AS IDENTITY, email text NOT NULL, status text NOT NULL DEFAULT 'active', payload jsonb, email_lower text GENERATED ALWAYS AS (lower(email)) STORED, CONSTRAINT accounts_pk PRIMARY KEY (id), CONSTRAINT accounts_id_status_key UNIQUE (id, status), CONSTRAINT accounts_email_key UNIQUE (email), CONSTRAINT accounts_status_check CHECK (status IN ('active','disabled')))`,
		`CREATE TABLE aoci_d0.orders (account_id bigint NOT NULL, account_status text NOT NULL, seq integer NOT NULL, payload jsonb, CONSTRAINT orders_pk PRIMARY KEY (account_id, seq), CONSTRAINT orders_account_fk FOREIGN KEY (account_id, account_status) REFERENCES aoci_d0.accounts(id, status) ON UPDATE CASCADE ON DELETE RESTRICT)`,
		`CREATE INDEX orders_payload_idx ON aoci_d0.orders USING gin (payload)`,
		`CREATE INDEX orders_active_idx ON aoci_d0.orders (account_id, seq DESC) WHERE account_status = 'active'`,
		`CREATE INDEX accounts_email_expr_idx ON aoci_d0.accounts ((lower(email))) INCLUDE (status)`,
		`CREATE TABLE aoci_d0.events (event_id bigint NOT NULL, created_at date NOT NULL, payload jsonb, PRIMARY KEY (event_id, created_at)) PARTITION BY RANGE (created_at)`,
		`CREATE TABLE aoci_d0.events_2026 PARTITION OF aoci_d0.events FOR VALUES FROM ('2026-01-01') TO ('2027-01-01')`,
		`CREATE TABLE "Quoted Schema"."Order Items" ("select" integer NOT NULL PRIMARY KEY, "MixedCase" text)`,
		`CREATE TABLE "Quoted Schema".accounts (id serial PRIMARY KEY, note text)`,
		`INSERT INTO aoci_d0.accounts(email, status, payload) VALUES ('` + businessSentinel + `', 'active', '{"sentinel":"` + businessSentinel + `"}')`,
		`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname='aoci_d0_reader') THEN CREATE ROLE aoci_d0_reader LOGIN PASSWORD '` + credentialSentinel + `'; ELSE ALTER ROLE aoci_d0_reader PASSWORD '` + credentialSentinel + `'; END IF; END $$`,
		`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname='aoci_d0_partial') THEN CREATE ROLE aoci_d0_partial LOGIN PASSWORD '` + credentialSentinel + `'; ELSE ALTER ROLE aoci_d0_partial PASSWORD '` + credentialSentinel + `'; END IF; END $$`,
		`GRANT CONNECT ON DATABASE postgres TO aoci_d0_reader`,
		`GRANT CONNECT ON DATABASE postgres TO aoci_d0_partial`,
		`GRANT USAGE ON SCHEMA aoci_d0, "Quoted Schema" TO aoci_d0_reader`,
		`GRANT SELECT ON ALL TABLES IN SCHEMA aoci_d0, "Quoted Schema" TO aoci_d0_reader`,
		`GRANT USAGE ON SCHEMA aoci_d0 TO aoci_d0_partial`,
		`GRANT SELECT ON ALL TABLES IN SCHEMA aoci_d0 TO aoci_d0_partial`,
	}
	execIntegrationSQL(t, admin, postgresSetup)
	defer execIntegrationSQL(t, admin, []string{`DROP SCHEMA IF EXISTS aoci_d0 CASCADE`, `DROP SCHEMA IF EXISTS "Quoted Schema" CASCADE`, `REVOKE CONNECT ON DATABASE postgres FROM aoci_d0_reader, aoci_d0_partial`, `DROP ROLE IF EXISTS aoci_d0_reader`, `DROP ROLE IF EXISTS aoci_d0_partial`})
	t.Setenv("AOCI_TEST_DATABASE_DSN", readerDSN)
	source := SourceConfig{SourceID: "pgtemp", Engine: EnginePostgreSQL, Database: "postgres", Namespaces: []string{"Quoted Schema", "aoci_d0"}, CredentialEnv: "AOCI_TEST_DATABASE_DSN", Enabled: true}
	collector := NewCollector()
	manifest, first, files, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	assertIntegrationEvidence(t, manifest, first, files, 6, credentialSentinel)
	assertEvidenceContains(t, files,
		`database://pgtemp/Quoted%20Schema/accounts`, `database://pgtemp/aoci_d0/accounts`,
		`"serial": true`, `"identity": "BY DEFAULT"`, `"generated": "ALWAYS"`,
		`orders_account_fk`, `accounts_id_status_key`, `orders_active_idx`,
		`"predicate":`, `"partitioned": true`, `"included": true`, `lower(email)`, `jsonb`)
	assertSystemNamespacesExcluded(t, first, "pg_catalog", "information_schema", "pg_toast")
	_, repeated, repeatedFiles, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	assertRepeatedSnapshotBytes(t, first, files, repeated, repeatedFiles)
	assertRealContextBoundaries(t, collector, source)
	root := t.TempDir()
	baseline, baselineBytes := acceptRealSnapshot(t, root, manifest, first, files)
	unchanged := CompareSnapshot(repeated, baseline, true)
	if unchanged.Summary.Unchanged != len(first.Tables) || unchanged.Summary.New+unchanged.Summary.Changed+unchanged.Summary.Removed != 0 {
		t.Fatalf("unexpected PostgreSQL unchanged report: %+v", unchanged.Summary)
	}
	assertPostgreSQLVisibilityBoundary(t, adminDSN, credentialSentinel, collector, source)
	assertRealSourceFaults(t, EnginePostgreSQL, adminDSN, credentialSentinel, collector, source)
	assertPostgreSQLCollectorInterruption(t, admin, readerDSN, collector, source)
	assertSavedEvidenceSurvivesFailure(t, root, collector, source, first.SourceSnapshotSHA256)
	execIntegrationSQL(t, admin, []string{
		`ALTER TABLE aoci_d0.accounts ADD COLUMN display_name text`,
		`CREATE TABLE aoci_d0.new_table (id bigint PRIMARY KEY)`,
		`GRANT SELECT ON aoci_d0.new_table TO aoci_d0_reader`,
		`DROP TABLE "Quoted Schema"."Order Items"`,
	})
	_, second, secondFiles, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	report := CompareSnapshot(second, baseline, true)
	if report.Summary.Changed != 1 || report.Summary.New != 1 || report.Summary.Removed != 1 {
		t.Fatalf("unexpected PostgreSQL drift: %+v", report)
	}
	assertUnrelatedTableStable(t, first, second, "database://pgtemp/aoci_d0/orders")
	assertBaselineUnchanged(t, root, baselineBytes)
	logRealAcceptance(t, "postgresql", first, baseline, report, "database://pgtemp/aoci_d0/accounts", files)
	assertNoIntegrationSentinels(t, manifest, second, secondFiles, credentialSentinel)
}

func TestMySQLRealCatalogCollectionAndDrift(t *testing.T) {
	adminDSN := mysqlAdminDSN(t)
	credentialSentinel := randomCredential(t)
	readerDSN := mysqlUserDSN(t, adminDSN, "aoci_d0_reader", credentialSentinel)
	admin, err := sql.Open("mysql", adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close()
	mysqlSetup := []string{
		`DROP TABLE IF EXISTS orders`, `DROP TABLE IF EXISTS accounts`, `DROP TABLE IF EXISTS audit_events`, "DROP TABLE IF EXISTS `Order Items`", "DROP TABLE IF EXISTS `select`", `DROP TABLE IF EXISTS new_table`,
		`CREATE TABLE accounts (id bigint NOT NULL AUTO_INCREMENT, email varchar(255) NOT NULL, status varchar(20) NOT NULL DEFAULT 'active', payload json, email_lower varchar(255) GENERATED ALWAYS AS (lower(email)) STORED, PRIMARY KEY (id), UNIQUE KEY accounts_id_status_key (id, status), UNIQUE KEY accounts_email_key (email), CONSTRAINT accounts_status_check CHECK (status IN ('active','disabled'))) ENGINE=InnoDB`,
		`CREATE TABLE orders (account_id bigint NOT NULL, account_status varchar(20) NOT NULL, seq int NOT NULL, note varchar(255), payload json, PRIMARY KEY (account_id, seq), CONSTRAINT orders_account_fk FOREIGN KEY (account_id, account_status) REFERENCES accounts(id, status) ON UPDATE CASCADE ON DELETE RESTRICT, KEY orders_note_prefix_idx (note(12)), KEY orders_payload_visible_idx (account_id, seq DESC), KEY orders_invisible_idx (account_status) INVISIBLE) ENGINE=InnoDB`,
		"CREATE TABLE `Order Items` (`select` int NOT NULL PRIMARY KEY, `MixedCase` varchar(20)) ENGINE=InnoDB",
		"CREATE TABLE `select` (id int NOT NULL PRIMARY KEY) ENGINE=InnoDB",
		`CREATE TABLE audit_events (event_id bigint NOT NULL, event_year int NOT NULL, payload json, PRIMARY KEY (event_id, event_year)) ENGINE=InnoDB PARTITION BY RANGE (event_year) (PARTITION p2025 VALUES LESS THAN (2026), PARTITION pmax VALUES LESS THAN MAXVALUE)`,
		`INSERT INTO accounts(email, status, payload) VALUES ('` + businessSentinel + `', 'active', JSON_OBJECT('sentinel','` + businessSentinel + `'))`,
		`DROP USER IF EXISTS 'aoci_d0_reader'@'%'`,
		`CREATE USER 'aoci_d0_reader'@'%' IDENTIFIED BY '` + credentialSentinel + `'`,
		`GRANT SELECT ON aoci_test.* TO 'aoci_d0_reader'@'%'`,
		`DROP USER IF EXISTS 'aoci_d0_partial'@'%'`,
		`CREATE USER 'aoci_d0_partial'@'%' IDENTIFIED BY '` + credentialSentinel + `'`,
		`GRANT SELECT ON aoci_test.accounts TO 'aoci_d0_partial'@'%'`,
		`GRANT SELECT ON aoci_test.orders TO 'aoci_d0_partial'@'%'`,
		`DROP USER IF EXISTS 'aoci_d0_interrupt'@'%'`,
		`CREATE USER 'aoci_d0_interrupt'@'%' IDENTIFIED BY '` + credentialSentinel + `'`,
		`GRANT SELECT ON aoci_test.* TO 'aoci_d0_interrupt'@'%'`,
	}
	execIntegrationSQL(t, admin, mysqlSetup)
	defer execIntegrationSQL(t, admin, []string{`DROP USER IF EXISTS 'aoci_d0_reader'@'%'`, `DROP USER IF EXISTS 'aoci_d0_partial'@'%'`, `DROP USER IF EXISTS 'aoci_d0_interrupt'@'%'`})
	t.Setenv("AOCI_TEST_DATABASE_DSN", readerDSN)
	source := SourceConfig{SourceID: "mysqltemp", Engine: EngineMySQL, Database: "aoci_test", Namespaces: []string{"aoci_test"}, CredentialEnv: "AOCI_TEST_DATABASE_DSN", Enabled: true}
	collector := NewCollector()
	manifest, first, files, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	assertIntegrationEvidence(t, manifest, first, files, 5, credentialSentinel)
	assertEvidenceContains(t, files,
		`database://mysqltemp/aoci_test/Order%20Items`, `"auto_increment": true`,
		`"generated": "stored"`, `orders_account_fk`, `accounts_status_check`,
		`"prefix_length": 12`, `"visible": false`, `"descending": true`, `"definitions":`, `json`)
	assertSystemNamespacesExcluded(t, first, "information_schema", "mysql", "performance_schema", "sys")
	_, repeated, repeatedFiles, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	assertRepeatedSnapshotBytes(t, first, files, repeated, repeatedFiles)
	assertRealContextBoundaries(t, collector, source)
	if manifest.CaseSemantics.LowerCaseTableNames == nil {
		t.Fatal("lower_case_table_names was not captured")
	}
	root := t.TempDir()
	baseline, baselineBytes := acceptRealSnapshot(t, root, manifest, first, files)
	unchanged := CompareSnapshot(repeated, baseline, true)
	if unchanged.Summary.Unchanged != len(first.Tables) || unchanged.Summary.New+unchanged.Summary.Changed+unchanged.Summary.Removed != 0 {
		t.Fatalf("unexpected MySQL unchanged report: %+v", unchanged.Summary)
	}
	assertMySQLVisibilityBoundary(t, adminDSN, credentialSentinel, collector, source)
	assertRealSourceFaults(t, EngineMySQL, adminDSN, credentialSentinel, collector, source)
	assertMySQLCollectorInterruption(t, admin, adminDSN, credentialSentinel, collector, source)
	assertSavedEvidenceSurvivesFailure(t, root, collector, source, first.SourceSnapshotSHA256)
	execIntegrationSQL(t, admin, []string{
		`ALTER TABLE accounts ADD COLUMN display_name varchar(255)`,
		`CREATE TABLE new_table (id bigint PRIMARY KEY) ENGINE=InnoDB`,
		"DROP TABLE `select`",
	})
	_, second, secondFiles, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	report := CompareSnapshot(second, baseline, true)
	if report.Summary.Changed != 1 || report.Summary.New != 1 || report.Summary.Removed != 1 {
		t.Fatalf("unexpected MySQL drift: %+v", report)
	}
	assertUnrelatedTableStable(t, first, second, "database://mysqltemp/aoci_test/orders")
	assertBaselineUnchanged(t, root, baselineBytes)
	logRealAcceptance(t, "mysql", first, baseline, report, "database://mysqltemp/aoci_test/accounts", files)
	assertNoIntegrationSentinels(t, manifest, second, secondFiles, credentialSentinel)
}

func TestOpenGaussRealCatalogCollectionAndDrift(t *testing.T) {
	adminDSN := openGaussAdminDSN(t)
	if os.Getenv("AOCI_TEST_OPENGAUSS_DISPOSABLE") != "1" {
		t.Fatal("AOCI_TEST_OPENGAUSS_DISPOSABLE=1 is required before destructive openGauss fixture setup")
	}
	credentialSentinel := openGaussRandomCredential(t)
	partialCredential := openGaussRandomCredential(t)
	admin, err := sql.Open("opengauss", adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close()
	if err := admin.PingContext(context.Background()); err != nil {
		t.Fatal(err)
	}

	const (
		aDatabase   = "aoci_og_accept_a"
		pgDatabase  = "aoci_og_accept_pg"
		readerUser  = "aoci_og_reader"
		partialUser = "aoci_og_partial"
	)
	for _, database := range []string{aDatabase, pgDatabase} {
		openGaussDropDatabase(t, admin, database)
	}
	execIntegrationSQL(t, admin, []string{
		`DROP USER IF EXISTS ` + readerUser,
		`DROP USER IF EXISTS ` + partialUser,
		`CREATE USER ` + readerUser + ` PASSWORD '` + credentialSentinel + `'`,
		`CREATE USER ` + partialUser + ` PASSWORD '` + partialCredential + `'`,
	})
	t.Cleanup(func() {
		cleanup, err := sql.Open("opengauss", adminDSN)
		if err != nil {
			t.Errorf("temporary openGauss cleanup connection failed: %v", err)
			return
		}
		defer cleanup.Close()
		for _, database := range []string{aDatabase, pgDatabase} {
			openGaussDropDatabase(t, cleanup, database)
		}
		for _, statement := range []string{`DROP USER IF EXISTS ` + readerUser, `DROP USER IF EXISTS ` + partialUser} {
			if _, err := cleanup.ExecContext(context.Background(), statement); err != nil {
				t.Errorf("temporary openGauss user cleanup failed: %v", err)
			}
		}
	})
	execIntegrationSQL(t, admin, []string{
		`CREATE DATABASE ` + aDatabase + ` DBCOMPATIBILITY 'A'`,
		`CREATE DATABASE ` + pgDatabase + ` DBCOMPATIBILITY 'PG'`,
		`GRANT CONNECT ON DATABASE ` + aDatabase + ` TO ` + readerUser,
		`GRANT CONNECT ON DATABASE ` + aDatabase + ` TO ` + partialUser,
		`GRANT CONNECT ON DATABASE ` + pgDatabase + ` TO ` + readerUser,
		`GRANT CONNECT ON DATABASE ` + pgDatabase + ` TO ` + partialUser,
	})

	for _, profile := range []struct {
		compatibility string
		database      string
		sourceID      string
	}{
		{compatibility: "A", database: aDatabase, sourceID: "ogatempc"},
		{compatibility: "PG", database: pgDatabase, sourceID: "ogpgtemp"},
	} {
		profile := profile
		t.Run(profile.compatibility, func(t *testing.T) {
			databaseDSN := openGaussDatabaseDSN(t, adminDSN, profile.database)
			openGaussRunProfileAcceptance(t, databaseDSN,
				openGaussUserDSN(t, databaseDSN, readerUser, credentialSentinel),
				openGaussUserDSN(t, databaseDSN, partialUser, partialCredential),
				credentialSentinel, profile)
		})
	}
}

func openGaussRunProfileAcceptance(t *testing.T, databaseDSN, readerDSN, partialDSN, credentialSentinel string, profile struct {
	compatibility string
	database      string
	sourceID      string
}) {
	t.Helper()
	database, err := sql.Open("opengauss", databaseDSN)
	if err != nil {
		t.Fatal(err)
	}
	defer database.Close()
	execIntegrationSQL(t, database, []string{
		`CREATE SCHEMA aoci_og`,
		`CREATE SCHEMA aoci_hidden`,
		`CREATE SCHEMA "Quoted Schema"`,
		`CREATE TABLE aoci_hidden.no_schema_usage (id integer PRIMARY KEY)`,
		`CREATE TABLE aoci_hidden.partition_without_schema_usage (id bigint, occurred_at date) PARTITION BY RANGE (occurred_at) (PARTITION p2026 VALUES LESS THAN ('2027-01-01'))`,
		`CREATE TABLE aoci_og.accounts (id bigserial, email varchar(255) NOT NULL, status varchar(20) NOT NULL DEFAULT 'active', amount numeric(12,2), CONSTRAINT accounts_pk PRIMARY KEY (id, email), CONSTRAINT accounts_email_key UNIQUE (email), CONSTRAINT accounts_status_check CHECK (status IN ('active','disabled')))`,
		`CREATE TABLE aoci_og.orders (account_id bigint NOT NULL, account_email varchar(255) NOT NULL, seq integer NOT NULL, note text, CONSTRAINT orders_pk PRIMARY KEY (account_id, seq), CONSTRAINT orders_account_fk FOREIGN KEY (account_id, account_email) REFERENCES aoci_og.accounts(id, email) ON UPDATE CASCADE ON DELETE RESTRICT)`,
		`CREATE INDEX orders_note_idx ON aoci_og.orders (note)`,
		`CREATE INDEX accounts_status_desc_idx ON aoci_og.accounts (status DESC)`,
		`CREATE TABLE "Quoted Schema".accounts (id integer NOT NULL PRIMARY KEY, note text)`,
		`INSERT INTO aoci_og.accounts(email, status, amount) VALUES ('` + businessSentinel + `', 'active', 1.00)`,
		`GRANT USAGE ON SCHEMA aoci_og, "Quoted Schema" TO aoci_og_reader`,
		`GRANT SELECT ON ALL TABLES IN SCHEMA aoci_og, "Quoted Schema" TO aoci_og_reader`,
		`GRANT USAGE ON SCHEMA aoci_og TO aoci_og_partial`,
		`GRANT SELECT ON aoci_og.accounts TO aoci_og_partial`,
		`GRANT SELECT ON aoci_hidden.no_schema_usage TO aoci_og_partial`,
		`GRANT SELECT ON aoci_hidden.partition_without_schema_usage TO aoci_og_partial`,
	})
	reader, err := sql.Open("opengauss", readerDSN)
	if err != nil {
		t.Fatal(err)
	}
	defer reader.Close()
	if _, err := reader.ExecContext(context.Background(), `INSERT INTO aoci_og.accounts(email, status) VALUES ('must_not_write', 'active')`); err == nil {
		t.Fatal("openGauss Evidence credential was not read-only")
	}

	const credentialEnv = "AOCI_TEST_DATABASE_DSN"
	t.Setenv(credentialEnv, readerDSN)
	source := SourceConfig{
		SourceID: profile.sourceID, Engine: EngineOpenGauss, Database: profile.database,
		Namespaces:    []string{"Quoted Schema", "aoci_hidden", "aoci_og", "information_schema", "pg_catalog", "dbe_perf", "db4ai"},
		CredentialEnv: credentialEnv, Enabled: true,
	}
	collector := NewCollector()
	manifest, first, files, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		if sourceErrorCode(err) == "catalog_query_failed" {
			openGaussDiagnoseIndexFailure(t, database, source)
		}
		t.Fatal(err)
	}
	if manifest.Engine != EngineOpenGauss || !strings.Contains(manifest.ServerVersion, "6.0.5") || !strings.Contains(manifest.ServerVersion, "deployment OpenSourceCentralized") || !strings.Contains(manifest.ServerVersion, "compatibility "+profile.compatibility) {
		t.Fatalf("unexpected openGauss profile identity: %+v", manifest)
	}
	assertIntegrationEvidence(t, manifest, first, files, 3, credentialSentinel)
	assertEvidenceContains(t, files,
		`database://`+profile.sourceID+`/Quoted%20Schema/accounts`,
		`database://`+profile.sourceID+`/aoci_og/accounts`,
		`"serial": true`, `accounts_email_key`, `accounts_status_check`, `orders_account_fk`,
		`"update_action": "cascade"`, `"delete_action": "restrict"`,
		`accounts_status_desc_idx`, `"descending": true`, `"visible": true`)
	assertSystemNamespacesExcluded(t, first, "information_schema", "pg_catalog", "dbe_perf", "db4ai")
	_, repeated, repeatedFiles, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	assertRepeatedSnapshotBytes(t, first, files, repeated, repeatedFiles)
	assertOpenGaussPartialVisibility(t, collector, source, partialDSN)
	assertOpenGaussPartialPartitionVisibility(t, database, collector, source, partialDSN)
	assertOpenGaussCatalogProfileDefaults(t, database)
	assertRealContextBoundaries(t, collector, source)

	root := t.TempDir()
	baseline, baselineBytes := acceptRealSnapshot(t, root, manifest, first, files)
	unchanged := CompareSnapshot(repeated, baseline, true)
	if unchanged.Summary.Unchanged != len(first.Tables) || unchanged.Summary.New+unchanged.Summary.Changed+unchanged.Summary.Removed != 0 {
		t.Fatalf("unexpected openGauss unchanged report: %+v", unchanged.Summary)
	}
	assertOpenGaussSourceFaults(t, collector, source, databaseDSN, credentialSentinel)
	assertOpenGaussCatalogPermissionDenial(t, database, collector, source)
	assertOpenGaussCollectorInterruption(t, database, readerDSN, collector, source)
	if openGaussUsesTLS(t, readerDSN) {
		assertOpenGaussTLSBoundaries(t, readerDSN, collector, source, first, files)
	}
	assertSavedEvidenceSurvivesFailure(t, root, collector, source, first.SourceSnapshotSHA256)
	execIntegrationSQL(t, database, []string{
		`ALTER TABLE aoci_og.accounts ADD COLUMN display_name text`,
		`CREATE TABLE aoci_og.new_table (id bigint PRIMARY KEY)`,
		`GRANT SELECT ON aoci_og.new_table TO aoci_og_reader`,
		`DROP TABLE "Quoted Schema".accounts`,
	})
	_, second, secondFiles, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	report := CompareSnapshot(second, baseline, true)
	if report.Summary.Changed != 1 || report.Summary.New != 1 || report.Summary.Removed != 1 {
		t.Fatalf("unexpected openGauss drift: %+v", report)
	}
	assertUnrelatedTableStable(t, first, second, "database://"+profile.sourceID+"/aoci_og/orders")
	assertBaselineUnchanged(t, root, baselineBytes)
	assertNoIntegrationSentinels(t, manifest, second, secondFiles, credentialSentinel)
	logRealAcceptance(t, "opengauss", first, baseline, report, "database://"+profile.sourceID+"/aoci_og/accounts", files)

	execIntegrationSQL(t, database, []string{
		`CREATE VIEW aoci_og.accounts_view AS SELECT id, email FROM aoci_og.accounts`,
		`GRANT SELECT ON aoci_og.accounts_view TO aoci_og_reader`,
	})
	_, unsupported, unsupportedFiles, err := collector.Snapshot(context.Background(), source)
	if sourceErrorCode(err) != "unsupported_catalog_feature" || len(unsupported.Tables) != 0 || len(unsupportedFiles) != 0 {
		t.Fatalf("openGauss selected view did not fail closed: snapshot=%+v files=%d err=%v", unsupported, len(unsupportedFiles), err)
	}
	execIntegrationSQL(t, database, []string{`DROP VIEW aoci_og.accounts_view`})
	assertBaselineUnchanged(t, root, baselineBytes)

	execIntegrationSQL(t, database, []string{
		`CREATE TABLE aoci_og.unsupported_check (id integer, CONSTRAINT unsupported_check_state CHECK (id > 0) NO INHERIT)`,
		`GRANT SELECT ON aoci_og.unsupported_check TO aoci_og_reader`,
	})
	_, unsupported, unsupportedFiles, err = collector.Snapshot(context.Background(), source)
	if sourceErrorCode(err) != "unsupported_catalog_feature" || len(unsupported.Tables) != 0 || len(unsupportedFiles) != 0 {
		t.Fatalf("openGauss CHECK NO INHERIT did not fail closed: snapshot=%+v files=%d err=%v", unsupported, len(unsupportedFiles), err)
	}
	execIntegrationSQL(t, database, []string{`DROP TABLE aoci_og.unsupported_check`})
	assertBaselineUnchanged(t, root, baselineBytes)

	execIntegrationSQL(t, database, []string{
		`CREATE TABLE aoci_og.partitioned_events (id bigint, occurred_at date) PARTITION BY RANGE (occurred_at) (PARTITION p2026 VALUES LESS THAN ('2027-01-01'))`,
		`GRANT SELECT ON aoci_og.partitioned_events TO aoci_og_reader`,
	})
	_, unsupported, unsupportedFiles, err = collector.Snapshot(context.Background(), source)
	if sourceErrorCode(err) != "unsupported_catalog_feature" || len(unsupported.Tables) != 0 || len(unsupportedFiles) != 0 {
		t.Fatalf("openGauss partition did not fail closed: snapshot=%+v files=%d err=%v", unsupported, len(unsupportedFiles), err)
	}
	execIntegrationSQL(t, database, []string{`DROP TABLE aoci_og.partitioned_events`})
	assertBaselineUnchanged(t, root, baselineBytes)

	execIntegrationSQL(t, database, []string{
		`CREATE SCHEMA aoci_chain WITH BLOCKCHAIN`,
		`CREATE TABLE aoci_chain.chain_table (id integer PRIMARY KEY)`,
		`GRANT USAGE ON SCHEMA aoci_chain TO aoci_og_reader`,
		`GRANT SELECT ON aoci_chain.chain_table TO aoci_og_reader`,
	})
	blockchainSource := source
	blockchainSource.Namespaces = append(append([]string(nil), source.Namespaces...), "aoci_chain")
	_, unsupported, unsupportedFiles, err = collector.Snapshot(context.Background(), blockchainSource)
	if sourceErrorCode(err) != "unsupported_catalog_feature" || len(unsupported.Tables) != 0 || len(unsupportedFiles) != 0 {
		t.Fatalf("openGauss blockchain schema did not fail closed: snapshot=%+v files=%d err=%v", unsupported, len(unsupportedFiles), err)
	}
	assertBaselineUnchanged(t, root, baselineBytes)
}

func assertOpenGaussCatalogProfileDefaults(t *testing.T, database *sql.DB) {
	t.Helper()
	var unsupportedOrdinaryConstraints int
	err := database.QueryRowContext(context.Background(), `
SELECT count(*)
FROM pg_catalog.pg_constraint AS k
JOIN pg_catalog.pg_class AS c ON c.oid = k.conrelid
JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
WHERE n.nspname = 'aoci_og'
  AND (k.condeferrable OR k.condeferred OR NOT k.convalidated
       OR (k.contype = 'f' AND k.confmatchtype <> 'u')
       OR k.condisable OR k.consoft OR k.conopt
       OR COALESCE(pg_catalog.array_length(k.conincluding, 1), 0) <> 0
       OR (k.contype = 'c' AND k.connoinherit)
       OR NOT k.conislocal OR k.coninhcount <> 0)`).Scan(&unsupportedOrdinaryConstraints)
	if err != nil || unsupportedOrdinaryConstraints != 0 {
		t.Fatalf("ordinary openGauss constraint defaults left the supported profile: count=%d err=%v", unsupportedOrdinaryConstraints, err)
	}
	var blockchain bool
	if err := database.QueryRowContext(context.Background(), `SELECT nspblockchain FROM pg_catalog.pg_namespace WHERE nspname = 'aoci_og'`).Scan(&blockchain); err != nil || blockchain {
		t.Fatalf("ordinary openGauss schema has unexpected blockchain state: blockchain=%t err=%v", blockchain, err)
	}
}

func assertOpenGaussPartialPartitionVisibility(t *testing.T, database *sql.DB, collector *Collector, source SourceConfig, partialDSN string) {
	t.Helper()
	partial := source
	partial.CredentialEnv = "AOCI_TEST_OPENGAUSS_PARTIAL_PARTITION_DSN"
	t.Setenv(partial.CredentialEnv, partialDSN)
	revoked := false
	defer func() {
		if !revoked {
			if _, err := database.ExecContext(context.Background(), `REVOKE USAGE ON SCHEMA aoci_hidden FROM aoci_og_partial`); err != nil {
				t.Errorf("openGauss partial partition visibility recovery failed: %v", err)
			}
		}
	}()
	if _, err := database.ExecContext(context.Background(), `GRANT USAGE ON SCHEMA aoci_hidden TO aoci_og_partial`); err != nil {
		t.Fatalf("openGauss partial partition visibility setup failed: %v", err)
	}
	_, snapshot, files, err := collector.Snapshot(context.Background(), partial)
	if sourceErrorCode(err) != "unsupported_catalog_feature" || len(snapshot.Tables) != 0 || len(files) != 0 {
		t.Fatalf("visible openGauss partition did not fail closed: code=%s tables=%d files=%d", sourceErrorCode(err), len(snapshot.Tables), len(files))
	}
	if _, err := database.ExecContext(context.Background(), `REVOKE USAGE ON SCHEMA aoci_hidden FROM aoci_og_partial`); err != nil {
		t.Fatalf("openGauss partial partition visibility restoration failed: %v", err)
	}
	revoked = true
}

func assertOpenGaussCatalogPermissionDenial(t *testing.T, database *sql.DB, collector *Collector, source SourceConfig) {
	t.Helper()
	const relation = "pg_catalog.pg_partition"
	var before string
	if err := database.QueryRowContext(context.Background(), `
SELECT c.relacl::text
FROM pg_catalog.pg_class AS c
JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
WHERE n.nspname = 'pg_catalog' AND c.relname = 'pg_partition'`).Scan(&before); err != nil {
		t.Fatalf("openGauss catalog PUBLIC ACL inspection failed: %v", err)
	}
	publicSelect := false
	for _, entry := range strings.Split(strings.Trim(before, "{}"), ",") {
		if strings.HasPrefix(entry, "=r/") {
			publicSelect = true
			break
		}
	}
	if !publicSelect {
		t.Fatalf("openGauss catalog permission fixture requires an exact PUBLIC SELECT precondition: %s", before)
	}

	restored := false
	restore := func() error {
		if _, err := database.ExecContext(context.Background(), `GRANT SELECT ON `+relation+` TO PUBLIC`); err != nil {
			return err
		}
		var after string
		if err := database.QueryRowContext(context.Background(), `
SELECT c.relacl::text
FROM pg_catalog.pg_class AS c
JOIN pg_catalog.pg_namespace AS n ON n.oid = c.relnamespace
WHERE n.nspname = 'pg_catalog' AND c.relname = 'pg_partition'`).Scan(&after); err != nil {
			return err
		}
		if after != before {
			return fmt.Errorf("catalog ACL was not restored exactly: before=%s after=%s", before, after)
		}
		return nil
	}
	defer func() {
		if !restored {
			if err := restore(); err != nil {
				t.Errorf("openGauss catalog PUBLIC ACL recovery failed: %v", err)
			}
		}
	}()
	if _, err := database.ExecContext(context.Background(), `REVOKE SELECT ON `+relation+` FROM PUBLIC`); err != nil {
		t.Fatalf("openGauss catalog permission denial setup failed: %v", err)
	}
	_, snapshot, files, err := collector.Snapshot(context.Background(), source)
	if sourceErrorCode(err) != "permission_denied" || len(snapshot.Tables) != 0 || len(files) != 0 {
		t.Fatalf("openGauss catalog permission denial was not fail-closed: code=%s tables=%d files=%d", sourceErrorCode(err), len(snapshot.Tables), len(files))
	}
	if err := restore(); err != nil {
		t.Fatalf("openGauss catalog PUBLIC ACL restoration failed: %v", err)
	}
	restored = true
}

func openGaussUsesTLS(t *testing.T, dsn string) bool {
	t.Helper()
	configuration, err := opengauss.ParseConfigStrict(dsn)
	if err != nil {
		t.Fatal("openGauss integration DSN does not satisfy the strict runtime contract")
	}
	return configuration.TLSConfig != nil
}

func assertOpenGaussTLSBoundaries(t *testing.T, readerDSN string, collector *Collector, source SourceConfig, first Snapshot, firstFiles map[string][]byte) {
	t.Helper()
	wrongCAPath := openGaussWrongCA(t)
	wrongCADSN := openGaussDSNQueryParameter(t, readerDSN, "sslrootcert", wrongCAPath)
	wrongCASource := source
	wrongCASource.CredentialEnv = "AOCI_TEST_OPENGAUSS_WRONG_CA_DSN"
	wrongCACollector := &Collector{
		getenv: func(string) string { return wrongCADSN },
		open:   openDatabase,
	}

	configuration, err := opengauss.ParseConfigStrict(readerDSN)
	if err != nil || configuration.TLSConfig == nil {
		t.Fatal("openGauss TLS hostname fixture could not parse the verified connection")
	}
	addresses, err := net.DefaultResolver.LookupHost(context.Background(), configuration.Host)
	if err != nil || len(addresses) == 0 {
		t.Fatal("openGauss TLS hostname fixture could not resolve the verified host")
	}
	const wrongHostname = "aoci-invalid-hostname.example"
	configuration.Host = wrongHostname
	configuration.TLSConfig = configuration.TLSConfig.Clone()
	configuration.TLSConfig.ServerName = wrongHostname
	configuration.LookupFunc = func(context.Context, string) ([]string, error) {
		return append([]string(nil), addresses...), nil
	}
	wrongHostnameConnector, err := opengauss.NewConnectorConfig(configuration)
	if err != nil {
		t.Fatal("openGauss TLS hostname fixture could not construct its connector")
	}
	wrongHostnameSource := source
	wrongHostnameSource.CredentialEnv = "AOCI_TEST_OPENGAUSS_WRONG_HOSTNAME_DSN"
	wrongHostnameCollector := &Collector{
		getenv: func(string) string { return readerDSN },
		open: func(driverName, _ string) (*sql.DB, error) {
			if driverName != "opengauss" {
				return nil, fmt.Errorf("unexpected driver")
			}
			return sql.OpenDB(wrongHostnameConnector), nil
		},
	}

	var (
		wrongCAErr       error
		wrongHostnameErr error
		openErr          error
		pingErr          error
		cancelErr        error
		recoveryErr      error
		recollectionErr  error
		recoveredValue   int
		recollected      Snapshot
		recollectedFiles map[string][]byte
		cancelElapsed    time.Duration
	)
	stdout := captureIntegrationStdout(t, func() {
		wrongCAErr = snapshotError(wrongCACollector, wrongCASource)
		wrongHostnameErr = snapshotError(wrongHostnameCollector, wrongHostnameSource)

		var database *sql.DB
		database, openErr = openOpenGaussDatabase(readerDSN, nil)
		if openErr != nil {
			return
		}
		defer database.Close()
		database.SetMaxOpenConns(1)
		database.SetMaxIdleConns(1)
		pingErr = database.PingContext(context.Background())
		if pingErr != nil {
			return
		}
		ctx, cancel := context.WithTimeout(context.Background(), 150*time.Millisecond)
		started := time.Now()
		_, cancelErr = database.ExecContext(ctx, `SELECT pg_catalog.pg_sleep(30)`)
		cancelElapsed = time.Since(started)
		cancel()
		recoveryErr = database.QueryRowContext(context.Background(), `SELECT 1`).Scan(&recoveredValue)
		_, recollected, recollectedFiles, recollectionErr = collector.Snapshot(context.Background(), source)
	})

	if stdout != "" {
		t.Fatalf("openGauss TLS negative/cancel paths wrote %d bytes to stdout", len(stdout))
	}
	if sourceErrorCode(wrongCAErr) != "connection_failed" {
		t.Fatalf("openGauss TLS wrong-CA failure code=%s want=connection_failed", sourceErrorCode(wrongCAErr))
	}
	if sourceErrorCode(wrongHostnameErr) != "connection_failed" {
		t.Fatalf("openGauss TLS wrong-hostname failure code=%s want=connection_failed", sourceErrorCode(wrongHostnameErr))
	}
	if openErr != nil || pingErr != nil {
		t.Fatal("openGauss verified TLS connection was not usable before cancellation")
	}
	if cancelErr == nil || cancelElapsed > 5*time.Second {
		t.Fatalf("openGauss TLS long query was not cancelled promptly: elapsed=%s", cancelElapsed)
	}
	if recoveryErr != nil || recoveredValue != 1 {
		t.Fatal("openGauss connection pool was not reusable after TLS cancellation")
	}
	if recollectionErr != nil {
		t.Fatal("openGauss Collector was not reusable after TLS cancellation")
	}
	assertRepeatedSnapshotBytes(t, first, firstFiles, recollected, recollectedFiles)
}

func openGaussWrongCA(t *testing.T) string {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal("openGauss wrong-CA fixture generation failed")
	}
	now := time.Now()
	template := &x509.Certificate{
		SerialNumber:          big.NewInt(1),
		Subject:               pkix.Name{CommonName: "AOCI unrelated openGauss test CA"},
		NotBefore:             now.Add(-time.Hour),
		NotAfter:              now.Add(time.Hour),
		IsCA:                  true,
		BasicConstraintsValid: true,
		KeyUsage:              x509.KeyUsageCertSign,
	}
	certificate, err := x509.CreateCertificate(rand.Reader, template, template, &key.PublicKey, key)
	if err != nil {
		t.Fatal("openGauss wrong-CA fixture generation failed")
	}
	path := filepath.Join(t.TempDir(), "wrong-ca.crt")
	if err := os.WriteFile(path, pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certificate}), 0600); err != nil {
		t.Fatal("openGauss wrong-CA fixture write failed")
	}
	return path
}

func openGaussDSNQueryParameter(t *testing.T, dsn, name, value string) string {
	t.Helper()
	parsed, err := url.Parse(dsn)
	if err != nil || parsed.Scheme == "" || parsed.Host == "" {
		t.Fatal("openGauss TLS integration requires a URL-form admin DSN")
	}
	query := parsed.Query()
	query.Set(name, value)
	parsed.RawQuery = query.Encode()
	return parsed.String()
}

func captureIntegrationStdout(t *testing.T, fn func()) string {
	t.Helper()
	reader, writer, err := os.Pipe()
	if err != nil {
		t.Fatal("stdout capture setup failed")
	}
	original := os.Stdout
	os.Stdout = writer
	type captured struct {
		data []byte
		err  error
	}
	result := make(chan captured, 1)
	go func() {
		data, readErr := io.ReadAll(reader)
		result <- captured{data: data, err: readErr}
	}()
	fn()
	os.Stdout = original
	if err := writer.Close(); err != nil {
		t.Fatal("stdout capture close failed")
	}
	got := <-result
	if err := reader.Close(); err != nil || got.err != nil {
		t.Fatal("stdout capture read failed")
	}
	return string(got.data)
}

func assertOpenGaussCollectorInterruption(t *testing.T, admin *sql.DB, readerDSN string, collector *Collector, source SourceConfig) {
	t.Helper()
	parsed, err := url.Parse(readerDSN)
	if err != nil {
		t.Fatal(err)
	}
	query := parsed.Query()
	applicationName := "aoci_og_interrupt_" + strings.ToLower(strings.ReplaceAll(source.SourceID, "_", ""))
	query.Set("application_name", applicationName)
	parsed.RawQuery = query.Encode()
	interrupted := source
	interrupted.CredentialEnv = "AOCI_TEST_OPENGAUSS_INTERRUPTED_DSN"
	t.Setenv(interrupted.CredentialEnv, parsed.String())
	type result struct {
		snapshot Snapshot
		files    map[string][]byte
		err      error
	}
	resultChannel := make(chan result, 1)
	go func() {
		_, snapshot, files, err := collector.Snapshot(context.Background(), interrupted)
		resultChannel <- result{snapshot: snapshot, files: files, err: err}
	}()
	deadline := time.Now().Add(5 * time.Second)
	terminated := false
	for time.Now().Before(deadline) {
		var processID int
		err := admin.QueryRowContext(context.Background(), `SELECT pid FROM pg_catalog.pg_stat_activity WHERE application_name = $1 AND xact_start IS NOT NULL LIMIT 1`, applicationName).Scan(&processID)
		if err == nil {
			if _, err := admin.ExecContext(context.Background(), `SELECT pg_catalog.pg_terminate_backend($1)`, processID); err != nil {
				t.Fatalf("temporary openGauss connection termination failed: %v", err)
			}
			terminated = true
			break
		}
		if !errors.Is(err, sql.ErrNoRows) {
			t.Fatalf("temporary openGauss activity inspection failed: %v", err)
		}
		time.Sleep(time.Millisecond)
	}
	if !terminated {
		t.Fatal("temporary openGauss collector connection was not observed")
	}
	select {
	case got := <-resultChannel:
		if got.err == nil || len(got.snapshot.Tables) != 0 || len(got.files) != 0 {
			t.Fatal("interrupted openGauss collection produced Evidence")
		}
	case <-time.After(5 * time.Second):
		t.Fatal("interrupted openGauss collection did not return")
	}
}

func openGaussDiagnoseIndexFailure(t *testing.T, database *sql.DB, source SourceConfig) {
	t.Helper()
	tx, err := database.BeginTx(context.Background(), &sql.TxOptions{Isolation: sql.LevelRepeatableRead, ReadOnly: true})
	if err != nil {
		t.Fatalf("openGauss index diagnostic transaction failed: %v", err)
	}
	defer tx.Rollback()
	tables, err := openGaussTables(context.Background(), tx, source)
	if err == nil {
		err = openGaussColumns(context.Background(), tx, source, tables)
	}
	if err == nil {
		err = openGaussIndexes(context.Background(), tx, source, tables)
	}
	if err != nil {
		t.Fatalf("openGauss index catalog decode failed: %v", err)
	}
	t.Fatal("openGauss index stage failed outside its dedicated loader")
}

func assertOpenGaussPartialVisibility(t *testing.T, collector *Collector, source SourceConfig, partialDSN string) {
	t.Helper()
	partial := source
	partial.CredentialEnv = "AOCI_TEST_OPENGAUSS_PARTIAL_DSN"
	t.Setenv(partial.CredentialEnv, partialDSN)
	_, snapshot, files, err := collector.Snapshot(context.Background(), partial)
	if err != nil {
		t.Fatal(err)
	}
	want := "database://" + source.SourceID + "/aoci_og/accounts"
	if len(snapshot.Tables) != 1 || len(files) != 1 || snapshot.Tables[0].ObjectRef != want {
		t.Fatalf("openGauss partial reader crossed its grants: %+v", snapshot.Tables)
	}
}

func assertOpenGaussSourceFaults(t *testing.T, collector *Collector, source SourceConfig, adminDSN, credential string) {
	t.Helper()
	missing := source
	missing.CredentialEnv = "AOCI_TEST_OPENGAUSS_MISSING_DSN"
	t.Setenv(missing.CredentialEnv, "")
	assertSourceErrorCode(t, collector, missing, "credential_env_missing")

	disabled := source
	disabled.Enabled = false
	assertSourceErrorCode(t, collector, disabled, "source_disabled")

	auth := source
	auth.CredentialEnv = "AOCI_TEST_OPENGAUSS_WRONG_AUTH_DSN"
	t.Setenv(auth.CredentialEnv, wrongCredentialDSN(t, EngineOpenGauss, os.Getenv(source.CredentialEnv)))
	authErr := assertSourceErrorCode(t, collector, auth, "permission_denied")

	unknown := source
	unknown.CredentialEnv = "AOCI_TEST_OPENGAUSS_UNKNOWN_DB_DSN"
	t.Setenv(unknown.CredentialEnv, nonexistentDatabaseDSN(t, EngineOpenGauss, adminDSN))
	unknownErr := assertSourceErrorCode(t, collector, unknown, "connection_failed")

	for _, value := range []string{credential, os.Getenv(source.CredentialEnv), os.Getenv(auth.CredentialEnv)} {
		for _, err := range []error{authErr, unknownErr} {
			if value != "" && strings.Contains(err.Error(), value) {
				t.Fatal("openGauss source error leaked credential or connection material")
			}
		}
	}
}

func openGaussDropDatabase(t *testing.T, admin *sql.DB, database string) {
	t.Helper()
	if _, err := admin.ExecContext(context.Background(), `DROP DATABASE IF EXISTS `+database); err != nil {
		t.Fatalf("temporary openGauss database cleanup failed: %v", err)
	}
}

func assertRepeatedSnapshotBytes(t *testing.T, first Snapshot, firstFiles map[string][]byte, second Snapshot, secondFiles map[string][]byte) {
	t.Helper()
	firstBytes, err := CanonicalJSON(first)
	if err != nil {
		t.Fatal(err)
	}
	secondBytes, err := CanonicalJSON(second)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(firstBytes, secondBytes) || !reflect.DeepEqual(firstFiles, secondFiles) {
		t.Fatal("repeated live catalog collection did not produce byte-identical canonical Evidence")
	}
}

func acceptRealSnapshot(t *testing.T, root string, manifest SourceManifest, snapshot Snapshot, files map[string][]byte) (Baseline, []byte) {
	t.Helper()
	if err := WriteSnapshot(root, manifest, snapshot, files); err != nil {
		t.Fatal(err)
	}
	if err := AcceptSnapshot(root, snapshot, snapshot.SourceSnapshotSHA256); err != nil {
		t.Fatal(err)
	}
	baseline, exists, err := LoadBaseline(root)
	if err != nil || !exists {
		t.Fatalf("real Evidence Baseline was not persisted: exists=%t err=%v", exists, err)
	}
	data, err := os.ReadFile(BaselinePath(root))
	if err != nil {
		t.Fatal(err)
	}
	return baseline, data
}

func assertBaselineUnchanged(t *testing.T, root string, accepted []byte) {
	t.Helper()
	current, err := os.ReadFile(BaselinePath(root))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(current, accepted) {
		t.Fatal("live drift verification advanced the Database Evidence Baseline")
	}
}

func assertUnrelatedTableStable(t *testing.T, before, after Snapshot, objectRef string) {
	t.Helper()
	beforeTable := snapshotRecord(t, before, objectRef)
	afterTable := snapshotRecord(t, after, objectRef)
	if beforeTable.TableEvidenceSHA256 != afterTable.TableEvidenceSHA256 {
		t.Fatalf("unrelated table fingerprint changed for %s", objectRef)
	}
}

func snapshotRecord(t *testing.T, snapshot Snapshot, objectRef string) SnapshotTable {
	t.Helper()
	for _, table := range snapshot.Tables {
		if table.ObjectRef == objectRef {
			return table
		}
	}
	t.Fatalf("snapshot omitted %s", objectRef)
	return SnapshotTable{}
}

func assertSystemNamespacesExcluded(t *testing.T, snapshot Snapshot, forbidden ...string) {
	t.Helper()
	for _, table := range snapshot.Tables {
		for _, namespace := range forbidden {
			if table.ObjectRef == "database://"+snapshot.SourceID+"/"+namespace || strings.Contains(table.ObjectRef, "/"+namespace+"/") {
				t.Fatalf("system namespace entered Evidence: %s", table.ObjectRef)
			}
		}
	}
}

func assertSavedEvidenceSurvivesFailure(t *testing.T, root string, collector *Collector, source SourceConfig, snapshotSHA string) {
	t.Helper()
	bad := source
	bad.CredentialEnv = "AOCI_TEST_DATABASE_FAILURE_DSN"
	t.Setenv(bad.CredentialEnv, unreachableDSN(t, source.Engine, os.Getenv(source.CredentialEnv)))
	if _, _, _, err := collector.Snapshot(context.Background(), bad); err == nil {
		t.Fatal("unavailable source unexpectedly produced Evidence")
	}
	_, stored, exists, err := LoadSnapshot(root, source.SourceID)
	if err != nil || !exists || stored.SourceSnapshotSHA256 != snapshotSHA {
		t.Fatalf("source failure damaged the previous saved Evidence: exists=%t err=%v", exists, err)
	}
}

func logRealAcceptance(t *testing.T, engine string, snapshot Snapshot, baseline Baseline, drift DriftReport, objectRef string, files map[string][]byte) {
	t.Helper()
	assertRealAcceptanceGolden(t, engine, snapshot, drift, objectRef, files)
	record := snapshotRecord(t, snapshot, objectRef)
	var acceptedSHA string
	for _, source := range baseline.Sources {
		if source.SourceID == snapshot.SourceID {
			acceptedSHA = source.SourceSnapshotSHA256
		}
	}
	if acceptedSHA != snapshot.SourceSnapshotSHA256 {
		t.Fatal("persisted Baseline is not bound to the accepted real snapshot")
	}
	table := TableEvidence{}
	if err := decodeStrict(files[objectRef], &table); err != nil {
		t.Fatal(err)
	}
	bundle := BuildEvidenceBundle(table, record.TableEvidenceSHA256, []string{"fixture://migration"}, []string{"fixture://code"}, nil)
	bundleBytes, err := CanonicalJSON(bundle)
	if err != nil || bundle.SemanticCandidateIncluded || bundle.BusinessDataRead {
		t.Fatalf("unsafe Evidence Bundle: err=%v", err)
	}
	if strings.Contains(string(bundleBytes), "F:") || strings.Contains(string(bundleBytes), "R:") || strings.Contains(string(bundleBytes), businessSentinel) {
		t.Fatal("Evidence Bundle contained generated FRAS or business row data")
	}
	t.Logf("database_acceptance engine=%s object_ref=%s table_evidence_sha256=%s source_snapshot_sha256=%s baseline_source_snapshot_sha256=%s tables=%d drift_unchanged=%d drift_new=%d drift_changed=%d drift_removed=%d business_data_read=false", engine, objectRef, record.TableEvidenceSHA256, snapshot.SourceSnapshotSHA256, acceptedSHA, len(snapshot.Tables), drift.Summary.Unchanged, drift.Summary.New, drift.Summary.Changed, drift.Summary.Removed)
	t.Logf("canonical_table_evidence engine=%s base64=%s", engine, base64.StdEncoding.EncodeToString(files[objectRef]))
}

func assertRealAcceptanceGolden(t *testing.T, engine string, snapshot Snapshot, drift DriftReport, objectRef string, files map[string][]byte) {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "real", "acceptance.json"))
	if err != nil {
		t.Fatal(err)
	}
	var golden realAcceptanceGolden
	if err := decodeStrict(data, &golden); err != nil || golden.Version != "database-real-acceptance/v1" {
		t.Fatalf("invalid real acceptance Golden: %v", err)
	}
	for _, candidate := range golden.Engines {
		if candidate.Engine != engine || candidate.ObjectRef != objectRef {
			continue
		}
		record := snapshotRecord(t, snapshot, objectRef)
		if candidate.ObjectRef != objectRef || candidate.TableEvidenceSHA256 != record.TableEvidenceSHA256 || candidate.SourceSnapshotSHA256 != snapshot.SourceSnapshotSHA256 || candidate.TableCount != len(snapshot.Tables) || candidate.Drift != drift.Summary {
			t.Fatalf("real %s acceptance identity drifted: snapshot=%s table=%s count=%d drift=%+v", engine, snapshot.SourceSnapshotSHA256, record.TableEvidenceSHA256, len(snapshot.Tables), drift.Summary)
		}
		expected, err := os.ReadFile(candidate.CanonicalEvidenceRef)
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(expected, files[objectRef]) {
			t.Fatalf("real %s Canonical Table Evidence drifted from its reviewed Golden", engine)
		}
		return
	}
	t.Fatalf("real acceptance Golden omitted engine %s", engine)
}

func assertPostgreSQLVisibilityBoundary(t *testing.T, adminDSN, credential string, collector *Collector, source SourceConfig) {
	t.Helper()
	partial := source
	partial.CredentialEnv = "AOCI_TEST_DATABASE_PARTIAL_DSN"
	t.Setenv(partial.CredentialEnv, postgresqlUserDSN(t, adminDSN, "aoci_d0_partial", credential))
	_, snapshot, _, err := collector.Snapshot(context.Background(), partial)
	if err != nil {
		t.Fatal(err)
	}
	if len(snapshot.Tables) != 4 {
		t.Fatalf("PostgreSQL partial reader saw %d tables, want 4", len(snapshot.Tables))
	}
	for _, table := range snapshot.Tables {
		if !strings.Contains(table.ObjectRef, "/aoci_d0/") {
			t.Fatalf("PostgreSQL partial reader crossed its granted schema: %s", table.ObjectRef)
		}
	}

	admin, err := sql.Open("pgx", adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close()
	if _, err := admin.ExecContext(context.Background(), `REVOKE SELECT ON pg_catalog.pg_partitioned_table FROM PUBLIC`); err != nil {
		t.Fatal("temporary PostgreSQL metadata permission setup failed")
	}
	restored := false
	defer func() {
		if !restored {
			_, _ = admin.ExecContext(context.Background(), `GRANT SELECT ON pg_catalog.pg_partitioned_table TO PUBLIC`)
		}
	}()
	if _, _, _, err := collector.Snapshot(context.Background(), source); sourceErrorCode(err) != "permission_denied" {
		t.Fatalf("PostgreSQL metadata denial classification failed: %s", sourceErrorCode(err))
	}
	if _, err := admin.ExecContext(context.Background(), `GRANT SELECT ON pg_catalog.pg_partitioned_table TO PUBLIC`); err != nil {
		t.Fatal("temporary PostgreSQL metadata permission restoration failed")
	}
	restored = true
}

func assertMySQLVisibilityBoundary(t *testing.T, adminDSN, credential string, collector *Collector, source SourceConfig) {
	t.Helper()
	partial := source
	partial.CredentialEnv = "AOCI_TEST_DATABASE_PARTIAL_DSN"
	t.Setenv(partial.CredentialEnv, mysqlUserDSN(t, adminDSN, "aoci_d0_partial", credential))
	_, snapshot, _, err := collector.Snapshot(context.Background(), partial)
	if err != nil {
		t.Fatal(err)
	}
	if len(snapshot.Tables) != 2 {
		t.Fatalf("MySQL partial reader saw %d tables, want 2", len(snapshot.Tables))
	}
	for _, objectRef := range []string{"database://mysqltemp/aoci_test/accounts", "database://mysqltemp/aoci_test/orders"} {
		_ = snapshotRecord(t, snapshot, objectRef)
	}
	admin, err := sql.Open("mysql", adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close()
	execIntegrationSQL(t, admin, []string{
		`REVOKE SELECT ON aoci_test.accounts FROM 'aoci_d0_partial'@'%'`,
		`REVOKE SELECT ON aoci_test.orders FROM 'aoci_d0_partial'@'%'`,
	})
	t.Setenv(partial.CredentialEnv, mysqlNoDefaultDatabaseDSN(t, os.Getenv(partial.CredentialEnv)))
	_, empty, emptyFiles, err := collector.Snapshot(context.Background(), partial)
	if err != nil || empty.State != "present_empty" || len(empty.Tables) != 0 || len(emptyFiles) != 0 {
		t.Fatalf("MySQL inaccessible namespace was not present_empty: state=%s tables=%d err=%v", empty.State, len(empty.Tables), err)
	}
}

func assertRealSourceFaults(t *testing.T, engine Engine, adminDSN, credential string, collector *Collector, source SourceConfig) {
	t.Helper()
	missing := source
	missing.CredentialEnv = "AOCI_TEST_DATABASE_MISSING_DSN"
	t.Setenv(missing.CredentialEnv, "")
	assertSourceErrorCode(t, collector, missing, "credential_env_missing")

	disabled := source
	disabled.Enabled = false
	assertSourceErrorCode(t, collector, disabled, "source_disabled")

	empty := source
	empty.IncludeTables = []string{"aoci_no_matching_table_*"}
	_, emptySnapshot, emptyFiles, err := collector.Snapshot(context.Background(), empty)
	if err != nil || emptySnapshot.State != "present_empty" || len(emptySnapshot.Tables) != 0 || len(emptyFiles) != 0 {
		t.Fatalf("filtered source was not present_empty: state=%s tables=%d err=%v", emptySnapshot.State, len(emptySnapshot.Tables), err)
	}

	auth := source
	auth.CredentialEnv = "AOCI_TEST_DATABASE_WRONG_AUTH_DSN"
	t.Setenv(auth.CredentialEnv, wrongCredentialDSN(t, engine, os.Getenv(source.CredentialEnv)))
	authCode := "permission_denied"
	authErr := assertSourceErrorCode(t, collector, auth, authCode)

	missingDatabase := source
	missingDatabase.CredentialEnv = "AOCI_TEST_DATABASE_UNKNOWN_DB_DSN"
	t.Setenv(missingDatabase.CredentialEnv, nonexistentDatabaseDSN(t, engine, adminDSN))
	missingDatabaseErr := assertSourceErrorCode(t, collector, missingDatabase, "connection_failed")

	tls := source
	tls.CredentialEnv = "AOCI_TEST_DATABASE_BAD_TLS_DSN"
	t.Setenv(tls.CredentialEnv, strictTLSDSN(t, engine, os.Getenv(source.CredentialEnv)))
	tlsErr := assertSourceErrorCode(t, collector, tls, "connection_failed")

	timed := source
	timed.CredentialEnv = "AOCI_TEST_DATABASE_TIMEOUT_DSN"
	timed.ConnectTimeoutSeconds = 1
	t.Setenv(timed.CredentialEnv, blackholeDSN(t, engine, os.Getenv(source.CredentialEnv)))
	timeoutErr := assertSourceErrorCode(t, collector, timed, "timeout")

	errorsToScan := []error{authErr, missingDatabaseErr, tlsErr, timeoutErr}
	for _, value := range []string{credential, os.Getenv(source.CredentialEnv), os.Getenv(auth.CredentialEnv), os.Getenv(tls.CredentialEnv)} {
		for _, candidate := range errorsToScan {
			if candidate != nil && value != "" && strings.Contains(candidate.Error(), value) {
				t.Fatal("source error leaked credential or connection material")
			}
		}
	}
}

func assertPostgreSQLCollectorInterruption(t *testing.T, admin *sql.DB, readerDSN string, collector *Collector, source SourceConfig) {
	t.Helper()
	parsed, err := url.Parse(readerDSN)
	if err != nil {
		t.Fatal(err)
	}
	query := parsed.Query()
	query.Set("application_name", "aoci_d0_interrupt")
	parsed.RawQuery = query.Encode()
	interrupted := source
	interrupted.CredentialEnv = "AOCI_TEST_DATABASE_INTERRUPTED_DSN"
	t.Setenv(interrupted.CredentialEnv, parsed.String())
	type result struct {
		snapshot Snapshot
		files    map[string][]byte
		err      error
	}
	resultChannel := make(chan result, 1)
	go func() {
		_, snapshot, files, err := collector.Snapshot(context.Background(), interrupted)
		resultChannel <- result{snapshot: snapshot, files: files, err: err}
	}()
	deadline := time.Now().Add(5 * time.Second)
	terminated := false
	for time.Now().Before(deadline) {
		var processID int
		err := admin.QueryRowContext(context.Background(), `SELECT pid FROM pg_catalog.pg_stat_activity WHERE application_name = 'aoci_d0_interrupt' AND xact_start IS NOT NULL LIMIT 1`).Scan(&processID)
		if err == nil {
			if _, err := admin.ExecContext(context.Background(), `SELECT pg_catalog.pg_terminate_backend($1)`, processID); err != nil {
				t.Fatal("temporary PostgreSQL connection termination failed")
			}
			terminated = true
			break
		}
		if !errors.Is(err, sql.ErrNoRows) {
			t.Fatal("temporary PostgreSQL activity inspection failed")
		}
		time.Sleep(time.Millisecond)
	}
	if !terminated {
		t.Fatal("temporary PostgreSQL collector connection was not observed")
	}
	select {
	case got := <-resultChannel:
		if got.err == nil || len(got.snapshot.Tables) != 0 || len(got.files) != 0 {
			t.Fatal("interrupted PostgreSQL collection produced Evidence")
		}
	case <-time.After(5 * time.Second):
		t.Fatal("interrupted PostgreSQL collection did not return")
	}
}

func assertMySQLCollectorInterruption(t *testing.T, admin *sql.DB, adminDSN, credential string, collector *Collector, source SourceConfig) {
	t.Helper()
	interrupted := source
	interrupted.CredentialEnv = "AOCI_TEST_DATABASE_INTERRUPTED_DSN"
	t.Setenv(interrupted.CredentialEnv, mysqlUserDSN(t, adminDSN, "aoci_d0_interrupt", credential))
	type result struct {
		snapshot Snapshot
		files    map[string][]byte
		err      error
	}
	resultChannel := make(chan result, 1)
	go func() {
		_, snapshot, files, err := collector.Snapshot(context.Background(), interrupted)
		resultChannel <- result{snapshot: snapshot, files: files, err: err}
	}()
	deadline := time.Now().Add(5 * time.Second)
	terminated := false
	for time.Now().Before(deadline) {
		var processID int64
		err := admin.QueryRowContext(context.Background(), `SELECT ID FROM information_schema.PROCESSLIST WHERE USER = 'aoci_d0_interrupt' LIMIT 1`).Scan(&processID)
		if err == nil {
			if _, err := admin.ExecContext(context.Background(), fmt.Sprintf("KILL CONNECTION %d", processID)); err != nil {
				t.Fatal("temporary MySQL connection termination failed")
			}
			terminated = true
			break
		}
		if !errors.Is(err, sql.ErrNoRows) {
			t.Fatal("temporary MySQL activity inspection failed")
		}
		time.Sleep(time.Millisecond)
	}
	if !terminated {
		t.Fatal("temporary MySQL collector connection was not observed")
	}
	select {
	case got := <-resultChannel:
		if got.err == nil || len(got.snapshot.Tables) != 0 || len(got.files) != 0 {
			t.Fatal("interrupted MySQL collection produced Evidence")
		}
	case <-time.After(5 * time.Second):
		t.Fatal("interrupted MySQL collection did not return")
	}
}

func snapshotError(collector *Collector, source SourceConfig) error {
	_, _, _, err := collector.Snapshot(context.Background(), source)
	return err
}

func assertSourceErrorCode(t *testing.T, collector *Collector, source SourceConfig, expected string) error {
	t.Helper()
	err := snapshotError(collector, source)
	if sourceErrorCode(err) != expected {
		var sourceErr *SourceError
		op := "none"
		if errors.As(err, &sourceErr) {
			op = sourceErr.Op
		}
		t.Fatalf("database source failure code=%s op=%s want=%s", sourceErrorCode(err), op, expected)
	}
	return err
}

func mysqlNoDefaultDatabaseDSN(t *testing.T, original string) string {
	t.Helper()
	parsed, err := mysqlDriver.ParseDSN(original)
	if err != nil {
		t.Fatal(err)
	}
	parsed.DBName = ""
	return parsed.FormatDSN()
}

func wrongCredentialDSN(t *testing.T, engine Engine, original string) string {
	t.Helper()
	if engine == EnginePostgreSQL || engine == EngineOpenGauss {
		parsed, err := url.Parse(original)
		if err != nil {
			t.Fatal(err)
		}
		parsed.User = url.UserPassword(parsed.User.Username(), "aoci_intentionally_wrong_credential")
		return parsed.String()
	}
	parsed, err := mysqlDriver.ParseDSN(original)
	if err != nil {
		t.Fatal(err)
	}
	parsed.Passwd = "aoci_intentionally_wrong_credential"
	return parsed.FormatDSN()
}

func nonexistentDatabaseDSN(t *testing.T, engine Engine, original string) string {
	t.Helper()
	if engine == EnginePostgreSQL || engine == EngineOpenGauss {
		parsed, err := url.Parse(original)
		if err != nil {
			t.Fatal(err)
		}
		parsed.Path = "/aoci_database_that_does_not_exist"
		return parsed.String()
	}
	parsed, err := mysqlDriver.ParseDSN(original)
	if err != nil {
		t.Fatal(err)
	}
	parsed.DBName = "aoci_database_that_does_not_exist"
	return parsed.FormatDSN()
}

func strictTLSDSN(t *testing.T, engine Engine, original string) string {
	t.Helper()
	if engine == EnginePostgreSQL || engine == EngineOpenGauss {
		parsed, err := url.Parse(original)
		if err != nil {
			t.Fatal(err)
		}
		query := parsed.Query()
		query.Set("sslmode", "verify-full")
		parsed.RawQuery = query.Encode()
		return parsed.String()
	}
	parsed, err := mysqlDriver.ParseDSN(original)
	if err != nil {
		t.Fatal(err)
	}
	parsed.TLSConfig = "true"
	return parsed.FormatDSN()
}

func unreachableDSN(t *testing.T, engine Engine, original string) string {
	t.Helper()
	return replaceDSNAddress(t, engine, original, "127.0.0.1:1")
}

func blackholeDSN(t *testing.T, engine Engine, original string) string {
	t.Helper()
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	done := make(chan struct{})
	go func() {
		for {
			connection, err := listener.Accept()
			if err != nil {
				return
			}
			go func() {
				defer connection.Close()
				<-done
			}()
		}
	}()
	t.Cleanup(func() {
		close(done)
		_ = listener.Close()
	})
	return replaceDSNAddress(t, engine, original, listener.Addr().String())
}

func replaceDSNAddress(t *testing.T, engine Engine, original, address string) string {
	t.Helper()
	if engine == EnginePostgreSQL || engine == EngineOpenGauss {
		parsed, err := url.Parse(original)
		if err != nil {
			t.Fatal(err)
		}
		parsed.Host = address
		query := parsed.Query()
		query.Del("host")
		query.Del("port")
		parsed.RawQuery = query.Encode()
		return parsed.String()
	}
	parsed, err := mysqlDriver.ParseDSN(original)
	if err != nil {
		t.Fatal(err)
	}
	parsed.Addr = address
	return parsed.FormatDSN()
}

func assertEvidenceContains(t *testing.T, files map[string][]byte, fragments ...string) {
	t.Helper()
	var combined strings.Builder
	for _, data := range files {
		combined.Write(data)
	}
	for _, fragment := range fragments {
		if !strings.Contains(combined.String(), fragment) {
			t.Fatalf("integration Evidence omitted %q", fragment)
		}
	}
}

func assertRealContextBoundaries(t *testing.T, collector *Collector, source SourceConfig) {
	t.Helper()
	cancelled, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := collector.Inspect(cancelled, source); sourceErrorCode(err) != "cancelled" {
		t.Fatalf("real driver cancellation was not classified: %v", err)
	}
	timedOut, cancel := context.WithTimeout(context.Background(), time.Nanosecond)
	defer cancel()
	if _, err := collector.Inspect(timedOut, source); sourceErrorCode(err) != "timeout" {
		t.Fatalf("real driver timeout was not classified: %v", err)
	}
}

func sourceErrorCode(err error) string {
	var sourceErr *SourceError
	if errors.As(err, &sourceErr) {
		return sourceErr.Code
	}
	return ""
}

func execIntegrationSQL(t *testing.T, database *sql.DB, statements []string) {
	t.Helper()
	for _, statement := range statements {
		if _, err := database.ExecContext(context.Background(), statement); err != nil {
			t.Fatalf("temporary database setup failed: %v", err)
		}
	}
}

func assertIntegrationEvidence(t *testing.T, manifest SourceManifest, snapshot Snapshot, files map[string][]byte, minimumTables int, credential string) {
	t.Helper()
	if len(snapshot.Tables) < minimumTables || manifest.BusinessDataRead || snapshot.BusinessDataRead {
		t.Fatalf("incomplete integration snapshot: manifest=%+v snapshot=%+v", manifest, snapshot)
	}
	assertNoIntegrationSentinels(t, manifest, snapshot, files, credential)
}

func assertNoIntegrationSentinels(t *testing.T, manifest SourceManifest, snapshot Snapshot, files map[string][]byte, credentials ...string) {
	t.Helper()
	data, _ := CanonicalJSON(struct {
		Manifest SourceManifest    `json:"manifest"`
		Snapshot Snapshot          `json:"snapshot"`
		Files    map[string][]byte `json:"files"`
	}{manifest, snapshot, files})
	for _, sentinel := range append([]string{businessSentinel}, credentials...) {
		if sentinel == "" {
			continue
		}
		if strings.Contains(string(data), sentinel) {
			t.Fatal("database evidence leaked a protected sentinel")
		}
	}
}

func randomCredential(t *testing.T) string {
	t.Helper()
	raw := make([]byte, 10)
	if _, err := rand.Read(raw); err != nil {
		t.Fatal(err)
	}
	return "aoci_test_" + hex.EncodeToString(raw)
}

func postgresqlAdminDSN(t *testing.T) string {
	t.Helper()
	if direct := os.Getenv("AOCI_TEST_POSTGRES_ADMIN_DSN"); direct != "" {
		return direct
	}
	password := os.Getenv("AOCI_TEST_POSTGRES_ADMIN_PASSWORD")
	address := os.Getenv("AOCI_TEST_POSTGRES_ADMIN_ADDR")
	user := os.Getenv("AOCI_TEST_POSTGRES_ADMIN_USER")
	database := os.Getenv("AOCI_TEST_POSTGRES_ADMIN_DATABASE")
	if password == "" && address == "" && user == "" && database == "" {
		t.Skip("temporary PostgreSQL admin connection is not configured")
	}
	if password == "" || address == "" || user == "" || database == "" {
		t.Fatal("temporary PostgreSQL split admin connection is incomplete")
	}
	parsed := &url.URL{
		Scheme: "postgres",
		User:   url.UserPassword(user, password),
		Host:   address,
		Path:   database,
	}
	query := parsed.Query()
	query.Set("sslmode", "disable")
	parsed.RawQuery = query.Encode()
	return parsed.String()
}

func mysqlAdminDSN(t *testing.T) string {
	t.Helper()
	if direct := os.Getenv("AOCI_TEST_MYSQL_ADMIN_DSN"); direct != "" {
		return direct
	}
	address := os.Getenv("AOCI_TEST_MYSQL_ADMIN_ADDR")
	user := os.Getenv("AOCI_TEST_MYSQL_ADMIN_USER")
	database := os.Getenv("AOCI_TEST_MYSQL_ADMIN_DATABASE")
	if address == "" && user == "" && database == "" {
		t.Skip("temporary MySQL admin connection is not configured")
	}
	if address == "" || user == "" || database == "" {
		t.Fatal("temporary MySQL split admin connection is incomplete")
	}
	configuration := mysqlDriver.NewConfig()
	configuration.User = user
	configuration.Net = "tcp"
	configuration.Addr = address
	configuration.DBName = database
	return configuration.FormatDSN()
}

func openGaussAdminDSN(t *testing.T) string {
	t.Helper()
	if direct := os.Getenv("AOCI_TEST_OPENGAUSS_ADMIN_DSN"); direct != "" {
		return direct
	}
	password := os.Getenv("AOCI_TEST_OPENGAUSS_ADMIN_PASSWORD")
	address := os.Getenv("AOCI_TEST_OPENGAUSS_ADMIN_ADDR")
	user := os.Getenv("AOCI_TEST_OPENGAUSS_ADMIN_USER")
	database := os.Getenv("AOCI_TEST_OPENGAUSS_ADMIN_DATABASE")
	if password == "" && address == "" && user == "" && database == "" {
		t.Skip("temporary openGauss admin connection is not configured")
	}
	if password == "" || address == "" || user == "" || database == "" {
		t.Fatal("temporary openGauss split admin connection is incomplete")
	}
	parsed := &url.URL{
		Scheme: "postgres",
		User:   url.UserPassword(user, password),
		Host:   address,
		Path:   "/" + database,
	}
	query := parsed.Query()
	query.Set("sslmode", "disable")
	parsed.RawQuery = query.Encode()
	return parsed.String()
}

func openGaussDatabaseDSN(t *testing.T, adminDSN, database string) string {
	t.Helper()
	parsed, err := url.Parse(adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	parsed.Path = "/" + database
	return parsed.String()
}

func openGaussUserDSN(t *testing.T, databaseDSN, username, password string) string {
	t.Helper()
	parsed, err := url.Parse(databaseDSN)
	if err != nil {
		t.Fatal(err)
	}
	parsed.User = url.UserPassword(username, password)
	return parsed.String()
}

func openGaussRandomCredential(t *testing.T) string {
	t.Helper()
	raw := make([]byte, 10)
	if _, err := rand.Read(raw); err != nil {
		t.Fatal(err)
	}
	credential := "Aoci9!" + hex.EncodeToString(raw)
	if len(credential) != 26 || !strings.ContainsAny(credential, "ABCDEFGHIJKLMNOPQRSTUVWXYZ") ||
		!strings.ContainsAny(credential, "abcdefghijklmnopqrstuvwxyz") ||
		!strings.ContainsAny(credential, "0123456789") || !strings.ContainsAny(credential, "!@#$%^&*") {
		t.Fatal("generated openGauss credential violates the 8-32 character complexity contract")
	}
	return credential
}

func postgresqlUserDSN(t *testing.T, adminDSN, username, password string) string {
	t.Helper()
	parsed, err := url.Parse(adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	parsed.User = url.UserPassword(username, password)
	return parsed.String()
}

func mysqlUserDSN(t *testing.T, adminDSN, username, password string) string {
	t.Helper()
	parsed, err := mysqlDriver.ParseDSN(adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	parsed.User = username
	parsed.Passwd = password
	return parsed.FormatDSN()
}
