//go:build integration

package dbevidence

import (
	"bytes"
	"context"
	"crypto/rand"
	"database/sql"
	"encoding/base64"
	"encoding/hex"
	"errors"
	"fmt"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"

	mysqlDriver "github.com/go-sql-driver/mysql"
)

const businessSentinel = "AOCI_BUSINESS_ROW_SENTINEL_D0"

type realAcceptanceGolden struct {
	Version string                     `json:"version"`
	Engines []realAcceptanceEngineGold `json:"engines"`
}

type realAcceptanceEngineGold struct {
	Engine               string       `json:"engine"`
	ObjectRef            string       `json:"object_ref"`
	CanonicalEvidenceRef string       `json:"canonical_evidence_ref"`
	TableEvidenceSHA256  string       `json:"table_evidence_sha256"`
	SourceSnapshotSHA256 string       `json:"source_snapshot_sha256"`
	TableCount           int          `json:"table_count"`
	Drift                DriftSummary `json:"drift"`
}

func TestPostgreSQLRealCatalogCollectionAndDrift(t *testing.T) {
	adminDSN := postgresqlAdminDSN(t)
	credentialSentinel := randomCredential(t)
	readerDSN := postgresqlUserDSN(t, adminDSN, "aoci_d0_reader", credentialSentinel)
	admin, err := sql.Open("pgx", adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close()
	postgresSetup := []string{
		`DROP SCHEMA IF EXISTS aoci_d0 CASCADE`,
		`DROP SCHEMA IF EXISTS "Quoted Schema" CASCADE`,
		`CREATE SCHEMA aoci_d0`,
		`CREATE SCHEMA "Quoted Schema"`,
		`CREATE TABLE aoci_d0.accounts (id bigint GENERATED BY DEFAULT AS IDENTITY, email text NOT NULL, status text NOT NULL DEFAULT 'active', payload jsonb, email_lower text GENERATED ALWAYS AS (lower(email)) STORED, CONSTRAINT accounts_pk PRIMARY KEY (id), CONSTRAINT accounts_id_status_key UNIQUE (id, status), CONSTRAINT accounts_email_key UNIQUE (email), CONSTRAINT accounts_status_check CHECK (status IN ('active','disabled')))`,
		`CREATE TABLE aoci_d0.orders (account_id bigint NOT NULL, account_status text NOT NULL, seq integer NOT NULL, payload jsonb, CONSTRAINT orders_pk PRIMARY KEY (account_id, seq), CONSTRAINT orders_account_fk FOREIGN KEY (account_id, account_status) REFERENCES aoci_d0.accounts(id, status) ON UPDATE CASCADE ON DELETE RESTRICT)`,
		`CREATE INDEX orders_payload_idx ON aoci_d0.orders USING gin (payload)`,
		`CREATE INDEX orders_active_idx ON aoci_d0.orders (account_id, seq DESC) WHERE account_status = 'active'`,
		`CREATE INDEX accounts_email_expr_idx ON aoci_d0.accounts ((lower(email))) INCLUDE (status)`,
		`CREATE TABLE aoci_d0.events (event_id bigint NOT NULL, created_at date NOT NULL, payload jsonb, PRIMARY KEY (event_id, created_at)) PARTITION BY RANGE (created_at)`,
		`CREATE TABLE aoci_d0.events_2026 PARTITION OF aoci_d0.events FOR VALUES FROM ('2026-01-01') TO ('2027-01-01')`,
		`CREATE TABLE "Quoted Schema"."Order Items" ("select" integer NOT NULL PRIMARY KEY, "MixedCase" text)`,
		`CREATE TABLE "Quoted Schema".accounts (id serial PRIMARY KEY, note text)`,
		`INSERT INTO aoci_d0.accounts(email, status, payload) VALUES ('` + businessSentinel + `', 'active', '{"sentinel":"` + businessSentinel + `"}')`,
		`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname='aoci_d0_reader') THEN CREATE ROLE aoci_d0_reader LOGIN PASSWORD '` + credentialSentinel + `'; ELSE ALTER ROLE aoci_d0_reader PASSWORD '` + credentialSentinel + `'; END IF; END $$`,
		`DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname='aoci_d0_partial') THEN CREATE ROLE aoci_d0_partial LOGIN PASSWORD '` + credentialSentinel + `'; ELSE ALTER ROLE aoci_d0_partial PASSWORD '` + credentialSentinel + `'; END IF; END $$`,
		`GRANT CONNECT ON DATABASE postgres TO aoci_d0_reader`,
		`GRANT CONNECT ON DATABASE postgres TO aoci_d0_partial`,
		`GRANT USAGE ON SCHEMA aoci_d0, "Quoted Schema" TO aoci_d0_reader`,
		`GRANT SELECT ON ALL TABLES IN SCHEMA aoci_d0, "Quoted Schema" TO aoci_d0_reader`,
		`GRANT USAGE ON SCHEMA aoci_d0 TO aoci_d0_partial`,
		`GRANT SELECT ON ALL TABLES IN SCHEMA aoci_d0 TO aoci_d0_partial`,
	}
	execIntegrationSQL(t, admin, postgresSetup)
	defer execIntegrationSQL(t, admin, []string{`DROP SCHEMA IF EXISTS aoci_d0 CASCADE`, `DROP SCHEMA IF EXISTS "Quoted Schema" CASCADE`, `REVOKE CONNECT ON DATABASE postgres FROM aoci_d0_reader, aoci_d0_partial`, `DROP ROLE IF EXISTS aoci_d0_reader`, `DROP ROLE IF EXISTS aoci_d0_partial`})
	t.Setenv("AOCI_TEST_DATABASE_DSN", readerDSN)
	source := SourceConfig{SourceID: "pgtemp", Engine: EnginePostgreSQL, Database: "postgres", Namespaces: []string{"Quoted Schema", "aoci_d0"}, CredentialEnv: "AOCI_TEST_DATABASE_DSN", Enabled: true}
	collector := NewCollector()
	manifest, first, files, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	assertIntegrationEvidence(t, manifest, first, files, 6, credentialSentinel)
	assertEvidenceContains(t, files,
		`database://pgtemp/Quoted%20Schema/accounts`, `database://pgtemp/aoci_d0/accounts`,
		`"serial": true`, `"identity": "BY DEFAULT"`, `"generated": "ALWAYS"`,
		`orders_account_fk`, `accounts_id_status_key`, `orders_active_idx`,
		`"predicate":`, `"partitioned": true`, `"included": true`, `lower(email)`, `jsonb`)
	assertSystemNamespacesExcluded(t, first, "pg_catalog", "information_schema", "pg_toast")
	_, repeated, repeatedFiles, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	assertRepeatedSnapshotBytes(t, first, files, repeated, repeatedFiles)
	assertRealContextBoundaries(t, collector, source)
	root := t.TempDir()
	baseline, baselineBytes := acceptRealSnapshot(t, root, manifest, first, files)
	unchanged := CompareSnapshot(repeated, baseline, true)
	if unchanged.Summary.Unchanged != len(first.Tables) || unchanged.Summary.New+unchanged.Summary.Changed+unchanged.Summary.Removed != 0 {
		t.Fatalf("unexpected PostgreSQL unchanged report: %+v", unchanged.Summary)
	}
	assertPostgreSQLVisibilityBoundary(t, adminDSN, credentialSentinel, collector, source)
	assertRealSourceFaults(t, EnginePostgreSQL, adminDSN, credentialSentinel, collector, source)
	assertPostgreSQLCollectorInterruption(t, admin, readerDSN, collector, source)
	assertSavedEvidenceSurvivesFailure(t, root, collector, source, first.SourceSnapshotSHA256)
	execIntegrationSQL(t, admin, []string{
		`ALTER TABLE aoci_d0.accounts ADD COLUMN display_name text`,
		`CREATE TABLE aoci_d0.new_table (id bigint PRIMARY KEY)`,
		`GRANT SELECT ON aoci_d0.new_table TO aoci_d0_reader`,
		`DROP TABLE "Quoted Schema"."Order Items"`,
	})
	_, second, secondFiles, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	report := CompareSnapshot(second, baseline, true)
	if report.Summary.Changed != 1 || report.Summary.New != 1 || report.Summary.Removed != 1 {
		t.Fatalf("unexpected PostgreSQL drift: %+v", report)
	}
	assertUnrelatedTableStable(t, first, second, "database://pgtemp/aoci_d0/orders")
	assertBaselineUnchanged(t, root, baselineBytes)
	logRealAcceptance(t, "postgresql", first, baseline, report, "database://pgtemp/aoci_d0/accounts", files)
	assertNoIntegrationSentinels(t, manifest, second, secondFiles, credentialSentinel)
}

func TestMySQLRealCatalogCollectionAndDrift(t *testing.T) {
	adminDSN := mysqlAdminDSN(t)
	credentialSentinel := randomCredential(t)
	readerDSN := mysqlUserDSN(t, adminDSN, "aoci_d0_reader", credentialSentinel)
	admin, err := sql.Open("mysql", adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close()
	mysqlSetup := []string{
		`DROP TABLE IF EXISTS orders`, `DROP TABLE IF EXISTS accounts`, `DROP TABLE IF EXISTS audit_events`, "DROP TABLE IF EXISTS `Order Items`", "DROP TABLE IF EXISTS `select`", `DROP TABLE IF EXISTS new_table`,
		`CREATE TABLE accounts (id bigint NOT NULL AUTO_INCREMENT, email varchar(255) NOT NULL, status varchar(20) NOT NULL DEFAULT 'active', payload json, email_lower varchar(255) GENERATED ALWAYS AS (lower(email)) STORED, PRIMARY KEY (id), UNIQUE KEY accounts_id_status_key (id, status), UNIQUE KEY accounts_email_key (email), CONSTRAINT accounts_status_check CHECK (status IN ('active','disabled'))) ENGINE=InnoDB`,
		`CREATE TABLE orders (account_id bigint NOT NULL, account_status varchar(20) NOT NULL, seq int NOT NULL, note varchar(255), payload json, PRIMARY KEY (account_id, seq), CONSTRAINT orders_account_fk FOREIGN KEY (account_id, account_status) REFERENCES accounts(id, status) ON UPDATE CASCADE ON DELETE RESTRICT, KEY orders_note_prefix_idx (note(12)), KEY orders_payload_visible_idx (account_id, seq DESC), KEY orders_invisible_idx (account_status) INVISIBLE) ENGINE=InnoDB`,
		"CREATE TABLE `Order Items` (`select` int NOT NULL PRIMARY KEY, `MixedCase` varchar(20)) ENGINE=InnoDB",
		"CREATE TABLE `select` (id int NOT NULL PRIMARY KEY) ENGINE=InnoDB",
		`CREATE TABLE audit_events (event_id bigint NOT NULL, event_year int NOT NULL, payload json, PRIMARY KEY (event_id, event_year)) ENGINE=InnoDB PARTITION BY RANGE (event_year) (PARTITION p2025 VALUES LESS THAN (2026), PARTITION pmax VALUES LESS THAN MAXVALUE)`,
		`INSERT INTO accounts(email, status, payload) VALUES ('` + businessSentinel + `', 'active', JSON_OBJECT('sentinel','` + businessSentinel + `'))`,
		`DROP USER IF EXISTS 'aoci_d0_reader'@'%'`,
		`CREATE USER 'aoci_d0_reader'@'%' IDENTIFIED BY '` + credentialSentinel + `'`,
		`GRANT SELECT ON aoci_test.* TO 'aoci_d0_reader'@'%'`,
		`DROP USER IF EXISTS 'aoci_d0_partial'@'%'`,
		`CREATE USER 'aoci_d0_partial'@'%' IDENTIFIED BY '` + credentialSentinel + `'`,
		`GRANT SELECT ON aoci_test.accounts TO 'aoci_d0_partial'@'%'`,
		`GRANT SELECT ON aoci_test.orders TO 'aoci_d0_partial'@'%'`,
		`DROP USER IF EXISTS 'aoci_d0_interrupt'@'%'`,
		`CREATE USER 'aoci_d0_interrupt'@'%' IDENTIFIED BY '` + credentialSentinel + `'`,
		`GRANT SELECT ON aoci_test.* TO 'aoci_d0_interrupt'@'%'`,
	}
	execIntegrationSQL(t, admin, mysqlSetup)
	defer execIntegrationSQL(t, admin, []string{`DROP USER IF EXISTS 'aoci_d0_reader'@'%'`, `DROP USER IF EXISTS 'aoci_d0_partial'@'%'`, `DROP USER IF EXISTS 'aoci_d0_interrupt'@'%'`})
	t.Setenv("AOCI_TEST_DATABASE_DSN", readerDSN)
	source := SourceConfig{SourceID: "mysqltemp", Engine: EngineMySQL, Database: "aoci_test", Namespaces: []string{"aoci_test"}, CredentialEnv: "AOCI_TEST_DATABASE_DSN", Enabled: true}
	collector := NewCollector()
	manifest, first, files, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	assertIntegrationEvidence(t, manifest, first, files, 5, credentialSentinel)
	assertEvidenceContains(t, files,
		`database://mysqltemp/aoci_test/Order%20Items`, `"auto_increment": true`,
		`"generated": "stored"`, `orders_account_fk`, `accounts_status_check`,
		`"prefix_length": 12`, `"visible": false`, `"descending": true`, `"definitions":`, `json`)
	assertSystemNamespacesExcluded(t, first, "information_schema", "mysql", "performance_schema", "sys")
	_, repeated, repeatedFiles, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	assertRepeatedSnapshotBytes(t, first, files, repeated, repeatedFiles)
	assertRealContextBoundaries(t, collector, source)
	if manifest.CaseSemantics.LowerCaseTableNames == nil {
		t.Fatal("lower_case_table_names was not captured")
	}
	root := t.TempDir()
	baseline, baselineBytes := acceptRealSnapshot(t, root, manifest, first, files)
	unchanged := CompareSnapshot(repeated, baseline, true)
	if unchanged.Summary.Unchanged != len(first.Tables) || unchanged.Summary.New+unchanged.Summary.Changed+unchanged.Summary.Removed != 0 {
		t.Fatalf("unexpected MySQL unchanged report: %+v", unchanged.Summary)
	}
	assertMySQLVisibilityBoundary(t, adminDSN, credentialSentinel, collector, source)
	assertRealSourceFaults(t, EngineMySQL, adminDSN, credentialSentinel, collector, source)
	assertMySQLCollectorInterruption(t, admin, adminDSN, credentialSentinel, collector, source)
	assertSavedEvidenceSurvivesFailure(t, root, collector, source, first.SourceSnapshotSHA256)
	execIntegrationSQL(t, admin, []string{
		`ALTER TABLE accounts ADD COLUMN display_name varchar(255)`,
		`CREATE TABLE new_table (id bigint PRIMARY KEY) ENGINE=InnoDB`,
		"DROP TABLE `select`",
	})
	_, second, secondFiles, err := collector.Snapshot(context.Background(), source)
	if err != nil {
		t.Fatal(err)
	}
	report := CompareSnapshot(second, baseline, true)
	if report.Summary.Changed != 1 || report.Summary.New != 1 || report.Summary.Removed != 1 {
		t.Fatalf("unexpected MySQL drift: %+v", report)
	}
	assertUnrelatedTableStable(t, first, second, "database://mysqltemp/aoci_test/orders")
	assertBaselineUnchanged(t, root, baselineBytes)
	logRealAcceptance(t, "mysql", first, baseline, report, "database://mysqltemp/aoci_test/accounts", files)
	assertNoIntegrationSentinels(t, manifest, second, secondFiles, credentialSentinel)
}

func assertRepeatedSnapshotBytes(t *testing.T, first Snapshot, firstFiles map[string][]byte, second Snapshot, secondFiles map[string][]byte) {
	t.Helper()
	firstBytes, err := CanonicalJSON(first)
	if err != nil {
		t.Fatal(err)
	}
	secondBytes, err := CanonicalJSON(second)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(firstBytes, secondBytes) || !reflect.DeepEqual(firstFiles, secondFiles) {
		t.Fatal("repeated live catalog collection did not produce byte-identical canonical Evidence")
	}
}

func acceptRealSnapshot(t *testing.T, root string, manifest SourceManifest, snapshot Snapshot, files map[string][]byte) (Baseline, []byte) {
	t.Helper()
	if err := WriteSnapshot(root, manifest, snapshot, files); err != nil {
		t.Fatal(err)
	}
	if err := AcceptSnapshot(root, snapshot, snapshot.SourceSnapshotSHA256); err != nil {
		t.Fatal(err)
	}
	baseline, exists, err := LoadBaseline(root)
	if err != nil || !exists {
		t.Fatalf("real Evidence Baseline was not persisted: exists=%t err=%v", exists, err)
	}
	data, err := os.ReadFile(BaselinePath(root))
	if err != nil {
		t.Fatal(err)
	}
	return baseline, data
}

func assertBaselineUnchanged(t *testing.T, root string, accepted []byte) {
	t.Helper()
	current, err := os.ReadFile(BaselinePath(root))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(current, accepted) {
		t.Fatal("live drift verification advanced the Database Evidence Baseline")
	}
}

func assertUnrelatedTableStable(t *testing.T, before, after Snapshot, objectRef string) {
	t.Helper()
	beforeTable := snapshotRecord(t, before, objectRef)
	afterTable := snapshotRecord(t, after, objectRef)
	if beforeTable.TableEvidenceSHA256 != afterTable.TableEvidenceSHA256 {
		t.Fatalf("unrelated table fingerprint changed for %s", objectRef)
	}
}

func snapshotRecord(t *testing.T, snapshot Snapshot, objectRef string) SnapshotTable {
	t.Helper()
	for _, table := range snapshot.Tables {
		if table.ObjectRef == objectRef {
			return table
		}
	}
	t.Fatalf("snapshot omitted %s", objectRef)
	return SnapshotTable{}
}

func assertSystemNamespacesExcluded(t *testing.T, snapshot Snapshot, forbidden ...string) {
	t.Helper()
	for _, table := range snapshot.Tables {
		for _, namespace := range forbidden {
			if table.ObjectRef == "database://"+snapshot.SourceID+"/"+namespace || strings.Contains(table.ObjectRef, "/"+namespace+"/") {
				t.Fatalf("system namespace entered Evidence: %s", table.ObjectRef)
			}
		}
	}
}

func assertSavedEvidenceSurvivesFailure(t *testing.T, root string, collector *Collector, source SourceConfig, snapshotSHA string) {
	t.Helper()
	bad := source
	bad.CredentialEnv = "AOCI_TEST_DATABASE_FAILURE_DSN"
	t.Setenv(bad.CredentialEnv, unreachableDSN(t, source.Engine, os.Getenv(source.CredentialEnv)))
	if _, _, _, err := collector.Snapshot(context.Background(), bad); err == nil {
		t.Fatal("unavailable source unexpectedly produced Evidence")
	}
	_, stored, exists, err := LoadSnapshot(root, source.SourceID)
	if err != nil || !exists || stored.SourceSnapshotSHA256 != snapshotSHA {
		t.Fatalf("source failure damaged the previous saved Evidence: exists=%t err=%v", exists, err)
	}
}

func logRealAcceptance(t *testing.T, engine string, snapshot Snapshot, baseline Baseline, drift DriftReport, objectRef string, files map[string][]byte) {
	t.Helper()
	assertRealAcceptanceGolden(t, engine, snapshot, drift, objectRef, files)
	record := snapshotRecord(t, snapshot, objectRef)
	var acceptedSHA string
	for _, source := range baseline.Sources {
		if source.SourceID == snapshot.SourceID {
			acceptedSHA = source.SourceSnapshotSHA256
		}
	}
	if acceptedSHA != snapshot.SourceSnapshotSHA256 {
		t.Fatal("persisted Baseline is not bound to the accepted real snapshot")
	}
	table := TableEvidence{}
	if err := decodeStrict(files[objectRef], &table); err != nil {
		t.Fatal(err)
	}
	bundle := BuildEvidenceBundle(table, record.TableEvidenceSHA256, []string{"fixture://migration"}, []string{"fixture://code"}, nil)
	bundleBytes, err := CanonicalJSON(bundle)
	if err != nil || bundle.SemanticCandidateIncluded || bundle.BusinessDataRead {
		t.Fatalf("unsafe Evidence Bundle: err=%v", err)
	}
	if strings.Contains(string(bundleBytes), "F:") || strings.Contains(string(bundleBytes), "R:") || strings.Contains(string(bundleBytes), businessSentinel) {
		t.Fatal("Evidence Bundle contained generated FRAS or business row data")
	}
	t.Logf("database_acceptance engine=%s object_ref=%s table_evidence_sha256=%s source_snapshot_sha256=%s baseline_source_snapshot_sha256=%s tables=%d drift_unchanged=%d drift_new=%d drift_changed=%d drift_removed=%d business_data_read=false", engine, objectRef, record.TableEvidenceSHA256, snapshot.SourceSnapshotSHA256, acceptedSHA, len(snapshot.Tables), drift.Summary.Unchanged, drift.Summary.New, drift.Summary.Changed, drift.Summary.Removed)
	t.Logf("canonical_table_evidence engine=%s base64=%s", engine, base64.StdEncoding.EncodeToString(files[objectRef]))
}

func assertRealAcceptanceGolden(t *testing.T, engine string, snapshot Snapshot, drift DriftReport, objectRef string, files map[string][]byte) {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "real", "acceptance.json"))
	if err != nil {
		t.Fatal(err)
	}
	var golden realAcceptanceGolden
	if err := decodeStrict(data, &golden); err != nil || golden.Version != "database-real-acceptance/v1" {
		t.Fatalf("invalid real acceptance Golden: %v", err)
	}
	for _, candidate := range golden.Engines {
		if candidate.Engine != engine {
			continue
		}
		record := snapshotRecord(t, snapshot, objectRef)
		if candidate.ObjectRef != objectRef || candidate.TableEvidenceSHA256 != record.TableEvidenceSHA256 || candidate.SourceSnapshotSHA256 != snapshot.SourceSnapshotSHA256 || candidate.TableCount != len(snapshot.Tables) || candidate.Drift != drift.Summary {
			t.Fatalf("real %s acceptance identity drifted: snapshot=%s table=%s count=%d drift=%+v", engine, snapshot.SourceSnapshotSHA256, record.TableEvidenceSHA256, len(snapshot.Tables), drift.Summary)
		}
		expected, err := os.ReadFile(candidate.CanonicalEvidenceRef)
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(expected, files[objectRef]) {
			t.Fatalf("real %s Canonical Table Evidence drifted from its reviewed Golden", engine)
		}
		return
	}
	t.Fatalf("real acceptance Golden omitted engine %s", engine)
}

func assertPostgreSQLVisibilityBoundary(t *testing.T, adminDSN, credential string, collector *Collector, source SourceConfig) {
	t.Helper()
	partial := source
	partial.CredentialEnv = "AOCI_TEST_DATABASE_PARTIAL_DSN"
	t.Setenv(partial.CredentialEnv, postgresqlUserDSN(t, adminDSN, "aoci_d0_partial", credential))
	_, snapshot, _, err := collector.Snapshot(context.Background(), partial)
	if err != nil {
		t.Fatal(err)
	}
	if len(snapshot.Tables) != 4 {
		t.Fatalf("PostgreSQL partial reader saw %d tables, want 4", len(snapshot.Tables))
	}
	for _, table := range snapshot.Tables {
		if !strings.Contains(table.ObjectRef, "/aoci_d0/") {
			t.Fatalf("PostgreSQL partial reader crossed its granted schema: %s", table.ObjectRef)
		}
	}

	admin, err := sql.Open("pgx", adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close()
	if _, err := admin.ExecContext(context.Background(), `REVOKE SELECT ON pg_catalog.pg_partitioned_table FROM PUBLIC`); err != nil {
		t.Fatal("temporary PostgreSQL metadata permission setup failed")
	}
	restored := false
	defer func() {
		if !restored {
			_, _ = admin.ExecContext(context.Background(), `GRANT SELECT ON pg_catalog.pg_partitioned_table TO PUBLIC`)
		}
	}()
	if _, _, _, err := collector.Snapshot(context.Background(), source); sourceErrorCode(err) != "permission_denied" {
		t.Fatalf("PostgreSQL metadata denial classification failed: %s", sourceErrorCode(err))
	}
	if _, err := admin.ExecContext(context.Background(), `GRANT SELECT ON pg_catalog.pg_partitioned_table TO PUBLIC`); err != nil {
		t.Fatal("temporary PostgreSQL metadata permission restoration failed")
	}
	restored = true
}

func assertMySQLVisibilityBoundary(t *testing.T, adminDSN, credential string, collector *Collector, source SourceConfig) {
	t.Helper()
	partial := source
	partial.CredentialEnv = "AOCI_TEST_DATABASE_PARTIAL_DSN"
	t.Setenv(partial.CredentialEnv, mysqlUserDSN(t, adminDSN, "aoci_d0_partial", credential))
	_, snapshot, _, err := collector.Snapshot(context.Background(), partial)
	if err != nil {
		t.Fatal(err)
	}
	if len(snapshot.Tables) != 2 {
		t.Fatalf("MySQL partial reader saw %d tables, want 2", len(snapshot.Tables))
	}
	for _, objectRef := range []string{"database://mysqltemp/aoci_test/accounts", "database://mysqltemp/aoci_test/orders"} {
		_ = snapshotRecord(t, snapshot, objectRef)
	}
	admin, err := sql.Open("mysql", adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	defer admin.Close()
	execIntegrationSQL(t, admin, []string{
		`REVOKE SELECT ON aoci_test.accounts FROM 'aoci_d0_partial'@'%'`,
		`REVOKE SELECT ON aoci_test.orders FROM 'aoci_d0_partial'@'%'`,
	})
	t.Setenv(partial.CredentialEnv, mysqlNoDefaultDatabaseDSN(t, os.Getenv(partial.CredentialEnv)))
	_, empty, emptyFiles, err := collector.Snapshot(context.Background(), partial)
	if err != nil || empty.State != "present_empty" || len(empty.Tables) != 0 || len(emptyFiles) != 0 {
		t.Fatalf("MySQL inaccessible namespace was not present_empty: state=%s tables=%d err=%v", empty.State, len(empty.Tables), err)
	}
}

func assertRealSourceFaults(t *testing.T, engine Engine, adminDSN, credential string, collector *Collector, source SourceConfig) {
	t.Helper()
	missing := source
	missing.CredentialEnv = "AOCI_TEST_DATABASE_MISSING_DSN"
	t.Setenv(missing.CredentialEnv, "")
	assertSourceErrorCode(t, collector, missing, "credential_env_missing")

	disabled := source
	disabled.Enabled = false
	assertSourceErrorCode(t, collector, disabled, "source_disabled")

	empty := source
	empty.IncludeTables = []string{"aoci_no_matching_table_*"}
	_, emptySnapshot, emptyFiles, err := collector.Snapshot(context.Background(), empty)
	if err != nil || emptySnapshot.State != "present_empty" || len(emptySnapshot.Tables) != 0 || len(emptyFiles) != 0 {
		t.Fatalf("filtered source was not present_empty: state=%s tables=%d err=%v", emptySnapshot.State, len(emptySnapshot.Tables), err)
	}

	auth := source
	auth.CredentialEnv = "AOCI_TEST_DATABASE_WRONG_AUTH_DSN"
	t.Setenv(auth.CredentialEnv, wrongCredentialDSN(t, engine, os.Getenv(source.CredentialEnv)))
	authCode := "permission_denied"
	authErr := assertSourceErrorCode(t, collector, auth, authCode)

	missingDatabase := source
	missingDatabase.CredentialEnv = "AOCI_TEST_DATABASE_UNKNOWN_DB_DSN"
	t.Setenv(missingDatabase.CredentialEnv, nonexistentDatabaseDSN(t, engine, adminDSN))
	missingDatabaseErr := assertSourceErrorCode(t, collector, missingDatabase, "connection_failed")

	tls := source
	tls.CredentialEnv = "AOCI_TEST_DATABASE_BAD_TLS_DSN"
	t.Setenv(tls.CredentialEnv, strictTLSDSN(t, engine, os.Getenv(source.CredentialEnv)))
	tlsErr := assertSourceErrorCode(t, collector, tls, "connection_failed")

	timed := source
	timed.CredentialEnv = "AOCI_TEST_DATABASE_TIMEOUT_DSN"
	timed.ConnectTimeoutSeconds = 1
	t.Setenv(timed.CredentialEnv, blackholeDSN(t, engine, os.Getenv(source.CredentialEnv)))
	timeoutErr := assertSourceErrorCode(t, collector, timed, "timeout")

	errorsToScan := []error{authErr, missingDatabaseErr, tlsErr, timeoutErr}
	for _, value := range []string{credential, os.Getenv(source.CredentialEnv), os.Getenv(auth.CredentialEnv), os.Getenv(tls.CredentialEnv)} {
		for _, candidate := range errorsToScan {
			if candidate != nil && value != "" && strings.Contains(candidate.Error(), value) {
				t.Fatal("source error leaked credential or connection material")
			}
		}
	}
}

func assertPostgreSQLCollectorInterruption(t *testing.T, admin *sql.DB, readerDSN string, collector *Collector, source SourceConfig) {
	t.Helper()
	parsed, err := url.Parse(readerDSN)
	if err != nil {
		t.Fatal(err)
	}
	query := parsed.Query()
	query.Set("application_name", "aoci_d0_interrupt")
	parsed.RawQuery = query.Encode()
	interrupted := source
	interrupted.CredentialEnv = "AOCI_TEST_DATABASE_INTERRUPTED_DSN"
	t.Setenv(interrupted.CredentialEnv, parsed.String())
	type result struct {
		snapshot Snapshot
		files    map[string][]byte
		err      error
	}
	resultChannel := make(chan result, 1)
	go func() {
		_, snapshot, files, err := collector.Snapshot(context.Background(), interrupted)
		resultChannel <- result{snapshot: snapshot, files: files, err: err}
	}()
	deadline := time.Now().Add(5 * time.Second)
	terminated := false
	for time.Now().Before(deadline) {
		var processID int
		err := admin.QueryRowContext(context.Background(), `SELECT pid FROM pg_catalog.pg_stat_activity WHERE application_name = 'aoci_d0_interrupt' AND xact_start IS NOT NULL LIMIT 1`).Scan(&processID)
		if err == nil {
			if _, err := admin.ExecContext(context.Background(), `SELECT pg_catalog.pg_terminate_backend($1)`, processID); err != nil {
				t.Fatal("temporary PostgreSQL connection termination failed")
			}
			terminated = true
			break
		}
		if !errors.Is(err, sql.ErrNoRows) {
			t.Fatal("temporary PostgreSQL activity inspection failed")
		}
		time.Sleep(time.Millisecond)
	}
	if !terminated {
		t.Fatal("temporary PostgreSQL collector connection was not observed")
	}
	select {
	case got := <-resultChannel:
		if got.err == nil || len(got.snapshot.Tables) != 0 || len(got.files) != 0 {
			t.Fatal("interrupted PostgreSQL collection produced Evidence")
		}
	case <-time.After(5 * time.Second):
		t.Fatal("interrupted PostgreSQL collection did not return")
	}
}

func assertMySQLCollectorInterruption(t *testing.T, admin *sql.DB, adminDSN, credential string, collector *Collector, source SourceConfig) {
	t.Helper()
	interrupted := source
	interrupted.CredentialEnv = "AOCI_TEST_DATABASE_INTERRUPTED_DSN"
	t.Setenv(interrupted.CredentialEnv, mysqlUserDSN(t, adminDSN, "aoci_d0_interrupt", credential))
	type result struct {
		snapshot Snapshot
		files    map[string][]byte
		err      error
	}
	resultChannel := make(chan result, 1)
	go func() {
		_, snapshot, files, err := collector.Snapshot(context.Background(), interrupted)
		resultChannel <- result{snapshot: snapshot, files: files, err: err}
	}()
	deadline := time.Now().Add(5 * time.Second)
	terminated := false
	for time.Now().Before(deadline) {
		var processID int64
		err := admin.QueryRowContext(context.Background(), `SELECT ID FROM information_schema.PROCESSLIST WHERE USER = 'aoci_d0_interrupt' LIMIT 1`).Scan(&processID)
		if err == nil {
			if _, err := admin.ExecContext(context.Background(), fmt.Sprintf("KILL CONNECTION %d", processID)); err != nil {
				t.Fatal("temporary MySQL connection termination failed")
			}
			terminated = true
			break
		}
		if !errors.Is(err, sql.ErrNoRows) {
			t.Fatal("temporary MySQL activity inspection failed")
		}
		time.Sleep(time.Millisecond)
	}
	if !terminated {
		t.Fatal("temporary MySQL collector connection was not observed")
	}
	select {
	case got := <-resultChannel:
		if got.err == nil || len(got.snapshot.Tables) != 0 || len(got.files) != 0 {
			t.Fatal("interrupted MySQL collection produced Evidence")
		}
	case <-time.After(5 * time.Second):
		t.Fatal("interrupted MySQL collection did not return")
	}
}

func snapshotError(collector *Collector, source SourceConfig) error {
	_, _, _, err := collector.Snapshot(context.Background(), source)
	return err
}

func assertSourceErrorCode(t *testing.T, collector *Collector, source SourceConfig, expected string) error {
	t.Helper()
	err := snapshotError(collector, source)
	if sourceErrorCode(err) != expected {
		var sourceErr *SourceError
		op := "none"
		if errors.As(err, &sourceErr) {
			op = sourceErr.Op
		}
		t.Fatalf("database source failure code=%s op=%s want=%s", sourceErrorCode(err), op, expected)
	}
	return err
}

func mysqlNoDefaultDatabaseDSN(t *testing.T, original string) string {
	t.Helper()
	parsed, err := mysqlDriver.ParseDSN(original)
	if err != nil {
		t.Fatal(err)
	}
	parsed.DBName = ""
	return parsed.FormatDSN()
}

func wrongCredentialDSN(t *testing.T, engine Engine, original string) string {
	t.Helper()
	if engine == EnginePostgreSQL {
		parsed, err := url.Parse(original)
		if err != nil {
			t.Fatal(err)
		}
		parsed.User = url.UserPassword(parsed.User.Username(), "aoci_intentionally_wrong_credential")
		return parsed.String()
	}
	parsed, err := mysqlDriver.ParseDSN(original)
	if err != nil {
		t.Fatal(err)
	}
	parsed.Passwd = "aoci_intentionally_wrong_credential"
	return parsed.FormatDSN()
}

func nonexistentDatabaseDSN(t *testing.T, engine Engine, original string) string {
	t.Helper()
	if engine == EnginePostgreSQL {
		parsed, err := url.Parse(original)
		if err != nil {
			t.Fatal(err)
		}
		parsed.Path = "/aoci_database_that_does_not_exist"
		return parsed.String()
	}
	parsed, err := mysqlDriver.ParseDSN(original)
	if err != nil {
		t.Fatal(err)
	}
	parsed.DBName = "aoci_database_that_does_not_exist"
	return parsed.FormatDSN()
}

func strictTLSDSN(t *testing.T, engine Engine, original string) string {
	t.Helper()
	if engine == EnginePostgreSQL {
		parsed, err := url.Parse(original)
		if err != nil {
			t.Fatal(err)
		}
		query := parsed.Query()
		query.Set("sslmode", "verify-full")
		parsed.RawQuery = query.Encode()
		return parsed.String()
	}
	parsed, err := mysqlDriver.ParseDSN(original)
	if err != nil {
		t.Fatal(err)
	}
	parsed.TLSConfig = "true"
	return parsed.FormatDSN()
}

func unreachableDSN(t *testing.T, engine Engine, original string) string {
	t.Helper()
	return replaceDSNAddress(t, engine, original, "127.0.0.1:1")
}

func blackholeDSN(t *testing.T, engine Engine, original string) string {
	t.Helper()
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	done := make(chan struct{})
	go func() {
		for {
			connection, err := listener.Accept()
			if err != nil {
				return
			}
			go func() {
				defer connection.Close()
				<-done
			}()
		}
	}()
	t.Cleanup(func() {
		close(done)
		_ = listener.Close()
	})
	return replaceDSNAddress(t, engine, original, listener.Addr().String())
}

func replaceDSNAddress(t *testing.T, engine Engine, original, address string) string {
	t.Helper()
	if engine == EnginePostgreSQL {
		parsed, err := url.Parse(original)
		if err != nil {
			t.Fatal(err)
		}
		parsed.Host = address
		return parsed.String()
	}
	parsed, err := mysqlDriver.ParseDSN(original)
	if err != nil {
		t.Fatal(err)
	}
	parsed.Addr = address
	return parsed.FormatDSN()
}

func assertEvidenceContains(t *testing.T, files map[string][]byte, fragments ...string) {
	t.Helper()
	var combined strings.Builder
	for _, data := range files {
		combined.Write(data)
	}
	for _, fragment := range fragments {
		if !strings.Contains(combined.String(), fragment) {
			t.Fatalf("integration Evidence omitted %q", fragment)
		}
	}
}

func assertRealContextBoundaries(t *testing.T, collector *Collector, source SourceConfig) {
	t.Helper()
	cancelled, cancel := context.WithCancel(context.Background())
	cancel()
	if _, err := collector.Inspect(cancelled, source); sourceErrorCode(err) != "cancelled" {
		t.Fatalf("real driver cancellation was not classified: %v", err)
	}
	timedOut, cancel := context.WithTimeout(context.Background(), time.Nanosecond)
	defer cancel()
	if _, err := collector.Inspect(timedOut, source); sourceErrorCode(err) != "timeout" {
		t.Fatalf("real driver timeout was not classified: %v", err)
	}
}

func sourceErrorCode(err error) string {
	var sourceErr *SourceError
	if errors.As(err, &sourceErr) {
		return sourceErr.Code
	}
	return ""
}

func execIntegrationSQL(t *testing.T, database *sql.DB, statements []string) {
	t.Helper()
	for _, statement := range statements {
		if _, err := database.ExecContext(context.Background(), statement); err != nil {
			t.Fatalf("temporary database setup failed: %v", err)
		}
	}
}

func assertIntegrationEvidence(t *testing.T, manifest SourceManifest, snapshot Snapshot, files map[string][]byte, minimumTables int, credential string) {
	t.Helper()
	if len(snapshot.Tables) < minimumTables || manifest.BusinessDataRead || snapshot.BusinessDataRead {
		t.Fatalf("incomplete integration snapshot: manifest=%+v snapshot=%+v", manifest, snapshot)
	}
	assertNoIntegrationSentinels(t, manifest, snapshot, files, credential)
}

func assertNoIntegrationSentinels(t *testing.T, manifest SourceManifest, snapshot Snapshot, files map[string][]byte, credential string) {
	t.Helper()
	data, _ := CanonicalJSON(struct {
		Manifest SourceManifest    `json:"manifest"`
		Snapshot Snapshot          `json:"snapshot"`
		Files    map[string][]byte `json:"files"`
	}{manifest, snapshot, files})
	for _, sentinel := range []string{businessSentinel, credential} {
		if strings.Contains(string(data), sentinel) {
			t.Fatal("database evidence leaked a protected sentinel")
		}
	}
}

func randomCredential(t *testing.T) string {
	t.Helper()
	raw := make([]byte, 24)
	if _, err := rand.Read(raw); err != nil {
		t.Fatal(err)
	}
	return "aoci_test_" + hex.EncodeToString(raw)
}

func postgresqlAdminDSN(t *testing.T) string {
	t.Helper()
	if direct := os.Getenv("AOCI_TEST_POSTGRES_ADMIN_DSN"); direct != "" {
		return direct
	}
	password := os.Getenv("AOCI_TEST_POSTGRES_ADMIN_PASSWORD")
	address := os.Getenv("AOCI_TEST_POSTGRES_ADMIN_ADDR")
	user := os.Getenv("AOCI_TEST_POSTGRES_ADMIN_USER")
	database := os.Getenv("AOCI_TEST_POSTGRES_ADMIN_DATABASE")
	if password == "" && address == "" && user == "" && database == "" {
		t.Skip("temporary PostgreSQL admin connection is not configured")
	}
	if password == "" || address == "" || user == "" || database == "" {
		t.Fatal("temporary PostgreSQL split admin connection is incomplete")
	}
	parsed := &url.URL{
		Scheme: "postgres",
		User:   url.UserPassword(user, password),
		Host:   address,
		Path:   database,
	}
	query := parsed.Query()
	query.Set("sslmode", "disable")
	parsed.RawQuery = query.Encode()
	return parsed.String()
}

func mysqlAdminDSN(t *testing.T) string {
	t.Helper()
	if direct := os.Getenv("AOCI_TEST_MYSQL_ADMIN_DSN"); direct != "" {
		return direct
	}
	address := os.Getenv("AOCI_TEST_MYSQL_ADMIN_ADDR")
	user := os.Getenv("AOCI_TEST_MYSQL_ADMIN_USER")
	database := os.Getenv("AOCI_TEST_MYSQL_ADMIN_DATABASE")
	if address == "" && user == "" && database == "" {
		t.Skip("temporary MySQL admin connection is not configured")
	}
	if address == "" || user == "" || database == "" {
		t.Fatal("temporary MySQL split admin connection is incomplete")
	}
	configuration := mysqlDriver.NewConfig()
	configuration.User = user
	configuration.Net = "tcp"
	configuration.Addr = address
	configuration.DBName = database
	return configuration.FormatDSN()
}

func postgresqlUserDSN(t *testing.T, adminDSN, username, password string) string {
	t.Helper()
	parsed, err := url.Parse(adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	parsed.User = url.UserPassword(username, password)
	return parsed.String()
}

func mysqlUserDSN(t *testing.T, adminDSN, username, password string) string {
	t.Helper()
	parsed, err := mysqlDriver.ParseDSN(adminDSN)
	if err != nil {
		t.Fatal(err)
	}
	parsed.User = username
	parsed.Passwd = password
	return parsed.FormatDSN()
}
