// 指纹模型与基线读写。
// 索引条目: baseline.go[Base.Fp.9.S]
//
// 纪律:
//   - 原始SHA-256始终是内容绑定、CAS与平台content_hash互认的权威字节指纹;
//   - NormalizedSHA256只表达CRLF折叠为LF后的可选文本等价指纹;
//   - 是否允许换行等价由判定层显式决定，本文件不隐藏宽容策略;
//   - 旧Baseline缺少NormalizedSHA256时保持严格比较，不做静默迁移;
//   - Save写前滚动备份旧Baseline，正式写入经AtomicWrite;
//   - Size只用于展示，不参与等价判定。
package baseline

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/aoci-spec/aoci-code/internal/cognitionbudget"
	afs "github.com/aoci-spec/aoci-code/internal/fs"
	"github.com/aoci-spec/aoci-code/internal/machinecontract"
)

// Fingerprint 保存单文件的原始字节指纹与可选文本等价指纹。
type Fingerprint struct {
	// Role is additive Managed Scope state. An omitted role is legacy index,
	// preserving every Baseline v1 reader and old-project behavior.
	Role string `json:"role,omitempty"`
	// SHA256是原始文件字节的SHA-256，始终存在并保持严格语义。
	SHA256 string `json:"sha256"`

	// Size是实际读取的字节数，仅用于展示和诊断。
	Size int64 `json:"size,omitempty"`

	// NormalizedSHA256是仅将CRLF折叠为LF后的SHA-256。
	//
	// 只有满足文本嗅探且文件不超过安全上限时才生成。
	// 字段缺失可能表示旧Baseline、二进制文件或超限文件；
	// 判定层遇到任一侧缺失时必须退回原始SHA严格比较。
	NormalizedSHA256 string `json:"normalized_sha256,omitempty"`

	// FormatSHA256是受支持格式器生成的规范源码摘要。
	// 当前仅对可由go/format完整解析的.go文件生成；它只用于证明
	// gofmt表示变化，不参与CAS、Stage源码绑定或一般语义等价判断。
	FormatSHA256 string `json:"format_sha256,omitempty"`

	// FormatKind声明FormatSHA256使用的确定性格式器。
	FormatKind string `json:"format_kind,omitempty"`
}

// Baseline是.aoci/baseline.json的全量快照。
type Baseline struct {
	Version           int                        `json:"version"`
	CreatedAt         string                     `json:"created_at"`
	UpdatedAt         string                     `json:"updated_at"`
	Files             map[string]Fingerprint     `json:"files"`
	ManagedScope      *ManagedScopeState         `json:"managed_scope,omitempty"`
	DatabaseCognition *DatabaseCognitionBindings `json:"database_cognition,omitempty"`
}

type ManagedScopeState struct {
	Version              string                  `json:"version"`
	PolicyIdentity       string                  `json:"policy_identity"`
	ObserveChangePolicy  string                  `json:"observe_change_policy"`
	BudgetPolicyIdentity string                  `json:"budget_policy_identity,omitempty"`
	BudgetPolicy         *cognitionbudget.Policy `json:"budget_policy,omitempty"`
	// ApplyAuthorizationMode 记录产生本收据的那次事务所处的生效授权模式。
	// 团队配置只表达"期望";只有这里的收据才是"当前生效"的治理姿态,因此模式
	// 跃迁的方向可以被证明。放松(review→auto 等)继续形成显式Risk,是否自动
	// 授权由完整Preview的独立阻断器裁决。旧收据没有该字段,方向不可证,按失败关闭处理。
	ApplyAuthorizationMode string `json:"apply_authorization_mode,omitempty"`
	HighRiskApprovalDigest string `json:"high_risk_approval_digest,omitempty"`
}

// DatabaseCognitionBinding proves which complete model-authored table Entry
// was based on which canonical Table Evidence. It is intentionally stored in
// the existing cognition Baseline, not the independent Database Evidence
// Baseline, so Apply and recovery retain one governance transaction.
type DatabaseCognitionBinding struct {
	ObjectRef           string `json:"object_ref"`
	SourceID            string `json:"source_id"`
	EvidenceVersion     string `json:"evidence_version"`
	TableEvidenceSHA256 string `json:"table_evidence_sha256"`
	EntrySHA256         string `json:"entry_sha256"`
}

type DatabaseCognitionBindings struct {
	Version string                     `json:"version"`
	Entries []DatabaseCognitionBinding `json:"entries"`
}

// baselinePath返回Baseline文件的绝对路径。
func baselinePath(root string) string {
	return filepath.Join(root, ".aoci", "baseline.json")
}

// nowISO返回当前UTC ISO8601时间。
func nowISO() string {
	return time.Now().UTC().Format(time.RFC3339)
}

// NewBaseline以给定指纹集构造全新Baseline。
func NewBaseline(files map[string]Fingerprint) *Baseline {
	if files == nil {
		files = map[string]Fingerprint{}
	}

	now := nowISO()

	return &Baseline{
		Version:   1,
		CreatedAt: now,
		UpdatedAt: now,
		Files:     files,
	}
}

// NewBaselineAt constructs the exact Baseline postimage selected by a
// governance Prepare phase. The supplied UTC timestamp is part of that
// postimage and is never regenerated by Apply or recovery.
func NewBaselineAt(files map[string]Fingerprint, timestamp string) (*Baseline, error) {
	if files == nil {
		files = map[string]Fingerprint{}
	}
	parsed, err := time.Parse(time.RFC3339, timestamp)
	if err != nil || parsed.Location() != time.UTC {
		return nil, fmt.Errorf("baseline timestamp must be RFC3339 UTC")
	}
	return &Baseline{
		Version:   1,
		CreatedAt: timestamp,
		UpdatedAt: timestamp,
		Files:     files,
	}, nil
}

// MarshalExact encodes a preselected Baseline without changing timestamps.
// It is the shared serialization authority for digest-bound Prepare, Apply,
// Resume, and recovery comparisons.
func MarshalExact(baselineValue *Baseline) ([]byte, error) {
	if baselineValue == nil {
		return nil, fmt.Errorf("baseline is nil")
	}
	if baselineValue.Version != 1 || strings.TrimSpace(baselineValue.CreatedAt) == "" ||
		strings.TrimSpace(baselineValue.UpdatedAt) == "" || baselineValue.Files == nil {
		return nil, fmt.Errorf("baseline is incomplete")
	}
	if err := normalizeDatabaseCognitionBindings(baselineValue.DatabaseCognition); err != nil {
		return nil, fmt.Errorf("database cognition Baseline is invalid: %w", err)
	}
	if err := validateManagedScope(baselineValue); err != nil {
		return nil, fmt.Errorf("managed scope Baseline is invalid: %w", err)
	}
	data, err := json.MarshalIndent(baselineValue, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("serialize baseline: %w", err)
	}
	return append(data, '\n'), nil
}

// Load读取Baseline。
//
// 返回值为(Baseline, 是否存在, 错误)。
// 文件缺失返回(nil,false,nil)，不视为错误。
// 新增NormalizedSHA256使用omitempty，旧Version=1文件可直接兼容读取。
func Load(root string) (*Baseline, bool, error) {
	data, err := os.ReadFile(baselinePath(root))
	if err != nil {
		if os.IsNotExist(err) {
			return nil, false, nil
		}

		return nil, false, fmt.Errorf(
			"读取基线失败: %w",
			err,
		)
	}

	var baselineValue Baseline

	if err := json.Unmarshal(data, &baselineValue); err != nil {
		return nil, true, fmt.Errorf(
			"baseline.json 损坏(%v): 请人工核对后再决定是否重建Baseline",
			err,
		)
	}

	if baselineValue.Files == nil {
		baselineValue.Files = map[string]Fingerprint{}
	}
	if err := validateDatabaseCognitionBindings(baselineValue.DatabaseCognition); err != nil {
		return nil, true, fmt.Errorf("database cognition Baseline is invalid: %w", err)
	}
	if err := validateManagedScope(&baselineValue); err != nil {
		return nil, true, fmt.Errorf("managed scope Baseline is invalid: %w", err)
	}

	return &baselineValue, true, nil
}

// Save在共享索引锁内写入Baseline，供没有外层治理事务的调用方使用。
func Save(root string, baselineValue *Baseline) error {
	lock, err := afs.AcquireIndexLock(root)
	if err != nil {
		return fmt.Errorf("获取Baseline共享写锁失败: %w", err)
	}
	saveErr := SaveUnderIndexLock(root, baselineValue)
	releaseErr := lock.Release()
	if saveErr != nil {
		return saveErr
	}
	if releaseErr != nil {
		return fmt.Errorf("释放Baseline共享写锁失败: %w", releaseErr)
	}
	return nil
}

// SaveUnderIndexLock在调用方已经持有共享索引锁时写入Baseline。
// 写入前滚动备份旧文件，备份和正式文件均经AtomicWrite。调用者必须把
// Load/修改/Save完整包在同一锁域，避免scan与Entries等合法写入口互相覆盖。
func SaveUnderIndexLock(root string, baselineValue *Baseline) error {
	if err := normalizeDatabaseCognitionBindings(baselineValue.DatabaseCognition); err != nil {
		return fmt.Errorf("database cognition Baseline is invalid: %w", err)
	}
	path := baselinePath(root)

	if err := os.MkdirAll(
		filepath.Dir(path),
		0o755,
	); err != nil {
		return fmt.Errorf(
			"创建 .aoci 目录失败: %w",
			err,
		)
	}

	if old, err := os.ReadFile(path); err == nil {
		if err := afs.AtomicWrite(
			path+".bak",
			old,
		); err != nil {
			return fmt.Errorf(
				"备份旧基线失败: %w",
				err,
			)
		}
	}

	baselineValue.UpdatedAt = nowISO()

	data, err := MarshalExact(baselineValue)
	if err != nil {
		return fmt.Errorf("序列化基线失败: %w", err)
	}

	return afs.AtomicWrite(
		path,
		data,
	)
}

// FindDatabaseCognitionBinding returns a copy of the binding for objectRef.
func FindDatabaseCognitionBinding(baselineValue *Baseline, objectRef string) (DatabaseCognitionBinding, bool) {
	if baselineValue == nil || baselineValue.DatabaseCognition == nil {
		return DatabaseCognitionBinding{}, false
	}
	for _, binding := range baselineValue.DatabaseCognition.Entries {
		if binding.ObjectRef == objectRef {
			return binding, true
		}
	}
	return DatabaseCognitionBinding{}, false
}

// UpdateDatabaseCognitionBinding advances one table binding in the same
// in-memory Baseline that owns cognition file fingerprints. The caller remains
// responsible for saving it under the existing governance lock.
func UpdateDatabaseCognitionBinding(baselineValue *Baseline, binding DatabaseCognitionBinding) error {
	if baselineValue == nil {
		return fmt.Errorf("baseline is nil")
	}
	if baselineValue.DatabaseCognition == nil {
		baselineValue.DatabaseCognition = &DatabaseCognitionBindings{
			Version: machinecontract.DatabaseCognitionBindingVersion,
			Entries: []DatabaseCognitionBinding{},
		}
	}
	replaced := false
	for index := range baselineValue.DatabaseCognition.Entries {
		if baselineValue.DatabaseCognition.Entries[index].ObjectRef == binding.ObjectRef {
			baselineValue.DatabaseCognition.Entries[index] = binding
			replaced = true
			break
		}
	}
	if !replaced {
		baselineValue.DatabaseCognition.Entries = append(baselineValue.DatabaseCognition.Entries, binding)
	}
	return normalizeDatabaseCognitionBindings(baselineValue.DatabaseCognition)
}

// RemoveDatabaseCognitionBinding removes one explicitly governed orphan from
// the existing Database Cognition binding set. It does not delete Evidence or
// a database object and the caller remains responsible for the surrounding
// transaction and formal Volume update.
func RemoveDatabaseCognitionBinding(baselineValue *Baseline, objectRef string) error {
	if baselineValue == nil || baselineValue.DatabaseCognition == nil {
		return fmt.Errorf("database cognition binding is unavailable")
	}
	found := false
	entries := make([]DatabaseCognitionBinding, 0, len(baselineValue.DatabaseCognition.Entries))
	for _, binding := range baselineValue.DatabaseCognition.Entries {
		if binding.ObjectRef == objectRef {
			found = true
			continue
		}
		entries = append(entries, binding)
	}
	if !found {
		return fmt.Errorf("database cognition binding is missing")
	}
	baselineValue.DatabaseCognition.Entries = entries
	return normalizeDatabaseCognitionBindings(baselineValue.DatabaseCognition)
}

func normalizeDatabaseCognitionBindings(bindings *DatabaseCognitionBindings) error {
	if bindings == nil {
		return nil
	}
	sort.Slice(bindings.Entries, func(i, j int) bool {
		return bindings.Entries[i].ObjectRef < bindings.Entries[j].ObjectRef
	})
	return validateDatabaseCognitionBindings(bindings)
}

func validateDatabaseCognitionBindings(bindings *DatabaseCognitionBindings) error {
	if bindings == nil {
		return nil
	}
	if bindings.Version != machinecontract.DatabaseCognitionBindingVersion {
		return fmt.Errorf("unsupported binding version %q", bindings.Version)
	}
	previous := ""
	for _, binding := range bindings.Entries {
		parts := strings.Split(strings.TrimPrefix(binding.ObjectRef, "database://"), "/")
		validObjectRef := strings.HasPrefix(binding.ObjectRef, "database://") && len(parts) == 3 &&
			parts[0] == binding.SourceID && parts[0] != "" && parts[1] != "" && parts[2] != ""
		if binding.ObjectRef <= previous || !validObjectRef ||
			binding.SourceID == "" || binding.EvidenceVersion == "" ||
			!validBaselineSHA256(binding.TableEvidenceSHA256) || !validBaselineSHA256(binding.EntrySHA256) {
			return fmt.Errorf("invalid or duplicate binding for %q", binding.ObjectRef)
		}
		previous = binding.ObjectRef
	}
	return nil
}

func validBaselineSHA256(value string) bool {
	return len(value) == 64 && strings.Trim(value, "0123456789abcdef") == ""
}

func EffectiveRole(fingerprint Fingerprint) string {
	if fingerprint.Role == "" {
		return machinecontract.ScopeRoleIndex
	}
	return fingerprint.Role
}

func validateManagedScope(value *Baseline) error {
	if value == nil {
		return fmt.Errorf("baseline is nil")
	}
	for path, fingerprint := range value.Files {
		role := EffectiveRole(fingerprint)
		if role != machinecontract.ScopeRoleIndex && role != machinecontract.ScopeRoleObserve {
			return fmt.Errorf("invalid role for %q", path)
		}
	}
	if value.ManagedScope == nil {
		return nil
	}
	state := value.ManagedScope
	if state.Version != machinecontract.ManagedScopeBaselineV1 || !validBaselineSHA256(state.PolicyIdentity) ||
		(state.BudgetPolicyIdentity != "" && !validBaselineSHA256(state.BudgetPolicyIdentity)) ||
		(state.HighRiskApprovalDigest != "" && !validBaselineSHA256(state.HighRiskApprovalDigest)) ||
		(state.ObserveChangePolicy != machinecontract.ObserveChangeReviewRequired &&
			state.ObserveChangePolicy != machinecontract.ObserveChangeInformational) {
		return fmt.Errorf("managed scope state is incomplete")
	}
	if state.BudgetPolicy != nil {
		identity, err := cognitionbudget.Identity(*state.BudgetPolicy)
		if err != nil || identity != state.BudgetPolicyIdentity {
			return fmt.Errorf("managed scope budget policy binding is invalid")
		}
	}
	return nil
}

// UpdateOne前移单个文件的指纹。
//
// 调用方完成正式资产写入后再调用，并负责随后Save。
func UpdateOne(
	baselineValue *Baseline,
	relPath string,
	fingerprint Fingerprint,
) {
	if baselineValue.Files == nil {
		baselineValue.Files = map[string]Fingerprint{}
	}

	baselineValue.Files[relPath] = fingerprint
}
